package com.fit2cloud.plugin.container.sdk.constants;

/**
 * Created by liqiang on 2018/9/11.
 */
public enum PersistentVolumeType {

    AWS_EBS, AZURE_DISK, AZURE_FILE, CEPHFS, CINDER, CSI, FC, FLEX_VOLUME, FLOCKER, GCE_PERSISTENT_DISK, GLUSTERFS, HOST_PATH, ISCSI, LOCAL, NFS,
    PHOTON_PERSISTENT_DISK, PORTWORX_VOLUME, QUOBYTE, RBD, SCALE_IO, STORAGEOS, VSPHERE_VOLUME, UNKNOW

}
