package com.fit2cloud.mc.model;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

public class ModelVersion implements Serializable {
    @ApiModelProperty(value = "模块版本唯一标识", required = true)
    private String modelVersionUuid;

    @ApiModelProperty("创建时间")
    private Long created;

    @ApiModelProperty("描述")
    private String desctiption;

    @ApiModelProperty(value = "模块下载地址", required = true)
    private String downloadUrl;

    @ApiModelProperty(value = "模块版本", required = true)
    private String revision;

    @ApiModelProperty(value = "所属模块", required = true)
    private String modelBasicUuid;

    @ApiModelProperty(value = "安装时间", required = true)
    private Long installTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table model_version
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_version.model_version_uuid
     *
     * @return the value of model_version.model_version_uuid
     *
     * @mbg.generated
     */
    public String getModelVersionUuid() {
        return modelVersionUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_version.model_version_uuid
     *
     * @param modelVersionUuid the value for model_version.model_version_uuid
     *
     * @mbg.generated
     */
    public void setModelVersionUuid(String modelVersionUuid) {
        this.modelVersionUuid = modelVersionUuid == null ? null : modelVersionUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_version.created
     *
     * @return the value of model_version.created
     *
     * @mbg.generated
     */
    public Long getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_version.created
     *
     * @param created the value for model_version.created
     *
     * @mbg.generated
     */
    public void setCreated(Long created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_version.desctiption
     *
     * @return the value of model_version.desctiption
     *
     * @mbg.generated
     */
    public String getDesctiption() {
        return desctiption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_version.desctiption
     *
     * @param desctiption the value for model_version.desctiption
     *
     * @mbg.generated
     */
    public void setDesctiption(String desctiption) {
        this.desctiption = desctiption == null ? null : desctiption.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_version.download_url
     *
     * @return the value of model_version.download_url
     *
     * @mbg.generated
     */
    public String getDownloadUrl() {
        return downloadUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_version.download_url
     *
     * @param downloadUrl the value for model_version.download_url
     *
     * @mbg.generated
     */
    public void setDownloadUrl(String downloadUrl) {
        this.downloadUrl = downloadUrl == null ? null : downloadUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_version.revision
     *
     * @return the value of model_version.revision
     *
     * @mbg.generated
     */
    public String getRevision() {
        return revision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_version.revision
     *
     * @param revision the value for model_version.revision
     *
     * @mbg.generated
     */
    public void setRevision(String revision) {
        this.revision = revision == null ? null : revision.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_version.model_basic_uuid
     *
     * @return the value of model_version.model_basic_uuid
     *
     * @mbg.generated
     */
    public String getModelBasicUuid() {
        return modelBasicUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_version.model_basic_uuid
     *
     * @param modelBasicUuid the value for model_version.model_basic_uuid
     *
     * @mbg.generated
     */
    public void setModelBasicUuid(String modelBasicUuid) {
        this.modelBasicUuid = modelBasicUuid == null ? null : modelBasicUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_version.install_time
     *
     * @return the value of model_version.install_time
     *
     * @mbg.generated
     */
    public Long getInstallTime() {
        return installTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_version.install_time
     *
     * @param installTime the value for model_version.install_time
     *
     * @mbg.generated
     */
    public void setInstallTime(Long installTime) {
        this.installTime = installTime;
    }
}