package com.fit2cloud.mc.model;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

public class ModelManager implements Serializable {
    @ApiModelProperty(value = "模块环境唯一标识", required = true)
    private String uuid;

    @ApiModelProperty(value = "索引服务域名", required = true)
    private String modelAddress;

    @ApiModelProperty(value = "是否在线服务", required = true)
    private Boolean onLine;

    @ApiModelProperty(value = "运行环境", required = true)
    private String env;

    @ApiModelProperty("验证结果")
    private Integer validate;

    @ApiModelProperty("Docker registry 信息")
    private String dockerRegistry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table model_manager
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_manager.uuid
     *
     * @return the value of model_manager.uuid
     *
     * @mbg.generated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_manager.uuid
     *
     * @param uuid the value for model_manager.uuid
     *
     * @mbg.generated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_manager.model_address
     *
     * @return the value of model_manager.model_address
     *
     * @mbg.generated
     */
    public String getModelAddress() {
        return modelAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_manager.model_address
     *
     * @param modelAddress the value for model_manager.model_address
     *
     * @mbg.generated
     */
    public void setModelAddress(String modelAddress) {
        this.modelAddress = modelAddress == null ? null : modelAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_manager.on_line
     *
     * @return the value of model_manager.on_line
     *
     * @mbg.generated
     */
    public Boolean getOnLine() {
        return onLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_manager.on_line
     *
     * @param onLine the value for model_manager.on_line
     *
     * @mbg.generated
     */
    public void setOnLine(Boolean onLine) {
        this.onLine = onLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_manager.env
     *
     * @return the value of model_manager.env
     *
     * @mbg.generated
     */
    public String getEnv() {
        return env;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_manager.env
     *
     * @param env the value for model_manager.env
     *
     * @mbg.generated
     */
    public void setEnv(String env) {
        this.env = env == null ? null : env.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_manager.validate
     *
     * @return the value of model_manager.validate
     *
     * @mbg.generated
     */
    public Integer getValidate() {
        return validate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_manager.validate
     *
     * @param validate the value for model_manager.validate
     *
     * @mbg.generated
     */
    public void setValidate(Integer validate) {
        this.validate = validate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_manager.docker_registry
     *
     * @return the value of model_manager.docker_registry
     *
     * @mbg.generated
     */
    public String getDockerRegistry() {
        return dockerRegistry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_manager.docker_registry
     *
     * @param dockerRegistry the value for model_manager.docker_registry
     *
     * @mbg.generated
     */
    public void setDockerRegistry(String dockerRegistry) {
        this.dockerRegistry = dockerRegistry == null ? null : dockerRegistry.trim();
    }
}