package com.fit2cloud.commons.server.base.mapper;

import com.fit2cloud.commons.server.base.domain.CloudDatastore;
import com.fit2cloud.commons.server.base.domain.CloudDatastoreExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CloudDatastoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_datastore
     *
     * @mbg.generated
     */
    long countByExample(CloudDatastoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_datastore
     *
     * @mbg.generated
     */
    int deleteByExample(CloudDatastoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_datastore
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_datastore
     *
     * @mbg.generated
     */
    int insert(CloudDatastore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_datastore
     *
     * @mbg.generated
     */
    int insertSelective(CloudDatastore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_datastore
     *
     * @mbg.generated
     */
    List<CloudDatastore> selectByExample(CloudDatastoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_datastore
     *
     * @mbg.generated
     */
    CloudDatastore selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_datastore
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CloudDatastore record, @Param("example") CloudDatastoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_datastore
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CloudDatastore record, @Param("example") CloudDatastoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_datastore
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CloudDatastore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_datastore
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CloudDatastore record);
}