package com.fit2cloud.commons.server.base.mapper;

import com.fit2cloud.commons.server.base.domain.CloudImage;
import com.fit2cloud.commons.server.base.domain.CloudImageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CloudImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_image
     *
     * @mbg.generated
     */
    long countByExample(CloudImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_image
     *
     * @mbg.generated
     */
    int deleteByExample(CloudImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_image
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_image
     *
     * @mbg.generated
     */
    int insert(CloudImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_image
     *
     * @mbg.generated
     */
    int insertSelective(CloudImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_image
     *
     * @mbg.generated
     */
    List<CloudImage> selectByExampleWithBLOBs(CloudImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_image
     *
     * @mbg.generated
     */
    List<CloudImage> selectByExample(CloudImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_image
     *
     * @mbg.generated
     */
    CloudImage selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_image
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CloudImage record, @Param("example") CloudImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_image
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") CloudImage record, @Param("example") CloudImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_image
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CloudImage record, @Param("example") CloudImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_image
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CloudImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_image
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(CloudImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_image
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CloudImage record);
}