package com.fit2cloud.commons.server.base.mapper;

import com.fit2cloud.commons.server.base.domain.CloudAlarm;
import com.fit2cloud.commons.server.base.domain.CloudAlarmExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CloudAlarmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_alarm
     *
     * @mbg.generated
     */
    long countByExample(CloudAlarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_alarm
     *
     * @mbg.generated
     */
    int deleteByExample(CloudAlarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_alarm
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_alarm
     *
     * @mbg.generated
     */
    int insert(CloudAlarm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_alarm
     *
     * @mbg.generated
     */
    int insertSelective(CloudAlarm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_alarm
     *
     * @mbg.generated
     */
    List<CloudAlarm> selectByExample(CloudAlarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_alarm
     *
     * @mbg.generated
     */
    CloudAlarm selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_alarm
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CloudAlarm record, @Param("example") CloudAlarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_alarm
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CloudAlarm record, @Param("example") CloudAlarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_alarm
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CloudAlarm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_alarm
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CloudAlarm record);
}