package com.fit2cloud.commons.server.base.mapper;

import com.fit2cloud.commons.server.base.domain.CloudHost;
import com.fit2cloud.commons.server.base.domain.CloudHostExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CloudHostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_host
     *
     * @mbg.generated
     */
    long countByExample(CloudHostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_host
     *
     * @mbg.generated
     */
    int deleteByExample(CloudHostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_host
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_host
     *
     * @mbg.generated
     */
    int insert(CloudHost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_host
     *
     * @mbg.generated
     */
    int insertSelective(CloudHost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_host
     *
     * @mbg.generated
     */
    List<CloudHost> selectByExample(CloudHostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_host
     *
     * @mbg.generated
     */
    CloudHost selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_host
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CloudHost record, @Param("example") CloudHostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_host
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CloudHost record, @Param("example") CloudHostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_host
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CloudHost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_host
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CloudHost record);
}