package com.fit2cloud.commons.server.base.mapper;

import com.fit2cloud.commons.server.base.domain.CloudEvent;
import com.fit2cloud.commons.server.base.domain.CloudEventExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CloudEventMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_event
     *
     * @mbg.generated
     */
    long countByExample(CloudEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_event
     *
     * @mbg.generated
     */
    int deleteByExample(CloudEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_event
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_event
     *
     * @mbg.generated
     */
    int insert(CloudEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_event
     *
     * @mbg.generated
     */
    int insertSelective(CloudEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_event
     *
     * @mbg.generated
     */
    List<CloudEvent> selectByExample(CloudEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_event
     *
     * @mbg.generated
     */
    CloudEvent selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_event
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CloudEvent record, @Param("example") CloudEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_event
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CloudEvent record, @Param("example") CloudEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_event
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CloudEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_event
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CloudEvent record);
}