package com.fit2cloud.commons.server.base.mapper;

import com.fit2cloud.commons.server.base.domain.CloudServerCredential;
import com.fit2cloud.commons.server.base.domain.CloudServerCredentialExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CloudServerCredentialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_server_credential
     *
     * @mbg.generated
     */
    long countByExample(CloudServerCredentialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_server_credential
     *
     * @mbg.generated
     */
    int deleteByExample(CloudServerCredentialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_server_credential
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_server_credential
     *
     * @mbg.generated
     */
    int insert(CloudServerCredential record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_server_credential
     *
     * @mbg.generated
     */
    int insertSelective(CloudServerCredential record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_server_credential
     *
     * @mbg.generated
     */
    List<CloudServerCredential> selectByExampleWithBLOBs(CloudServerCredentialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_server_credential
     *
     * @mbg.generated
     */
    List<CloudServerCredential> selectByExample(CloudServerCredentialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_server_credential
     *
     * @mbg.generated
     */
    CloudServerCredential selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_server_credential
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CloudServerCredential record, @Param("example") CloudServerCredentialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_server_credential
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") CloudServerCredential record, @Param("example") CloudServerCredentialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_server_credential
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CloudServerCredential record, @Param("example") CloudServerCredentialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_server_credential
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CloudServerCredential record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_server_credential
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(CloudServerCredential record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_server_credential
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CloudServerCredential record);
}