package com.fit2cloud.commons.server.base.mapper;

import com.fit2cloud.commons.server.base.domain.CloudImageSyncSetting;
import com.fit2cloud.commons.server.base.domain.CloudImageSyncSettingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CloudImageSyncSettingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_image_sync_setting
     *
     * @mbg.generated
     */
    long countByExample(CloudImageSyncSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_image_sync_setting
     *
     * @mbg.generated
     */
    int deleteByExample(CloudImageSyncSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_image_sync_setting
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String cloudAccountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_image_sync_setting
     *
     * @mbg.generated
     */
    int insert(CloudImageSyncSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_image_sync_setting
     *
     * @mbg.generated
     */
    int insertSelective(CloudImageSyncSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_image_sync_setting
     *
     * @mbg.generated
     */
    List<CloudImageSyncSetting> selectByExampleWithBLOBs(CloudImageSyncSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_image_sync_setting
     *
     * @mbg.generated
     */
    List<CloudImageSyncSetting> selectByExample(CloudImageSyncSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_image_sync_setting
     *
     * @mbg.generated
     */
    CloudImageSyncSetting selectByPrimaryKey(String cloudAccountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_image_sync_setting
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CloudImageSyncSetting record, @Param("example") CloudImageSyncSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_image_sync_setting
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") CloudImageSyncSetting record, @Param("example") CloudImageSyncSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_image_sync_setting
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CloudImageSyncSetting record, @Param("example") CloudImageSyncSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_image_sync_setting
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CloudImageSyncSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_image_sync_setting
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(CloudImageSyncSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_image_sync_setting
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CloudImageSyncSetting record);
}