package com.fit2cloud.commons.server.base.mapper;

import com.fit2cloud.commons.server.base.domain.CloudCluster;
import com.fit2cloud.commons.server.base.domain.CloudClusterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CloudClusterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_cluster
     *
     * @mbg.generated
     */
    long countByExample(CloudClusterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_cluster
     *
     * @mbg.generated
     */
    int deleteByExample(CloudClusterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_cluster
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_cluster
     *
     * @mbg.generated
     */
    int insert(CloudCluster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_cluster
     *
     * @mbg.generated
     */
    int insertSelective(CloudCluster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_cluster
     *
     * @mbg.generated
     */
    List<CloudCluster> selectByExample(CloudClusterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_cluster
     *
     * @mbg.generated
     */
    CloudCluster selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_cluster
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CloudCluster record, @Param("example") CloudClusterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_cluster
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CloudCluster record, @Param("example") CloudClusterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_cluster
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CloudCluster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_cluster
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CloudCluster record);
}