package com.fit2cloud.commons.server.base.mapper;

import com.fit2cloud.commons.server.base.domain.CloudServer;
import com.fit2cloud.commons.server.base.domain.CloudServerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CloudServerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_server
     *
     * @mbg.generated
     */
    long countByExample(CloudServerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_server
     *
     * @mbg.generated
     */
    int deleteByExample(CloudServerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_server
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_server
     *
     * @mbg.generated
     */
    int insert(CloudServer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_server
     *
     * @mbg.generated
     */
    int insertSelective(CloudServer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_server
     *
     * @mbg.generated
     */
    List<CloudServer> selectByExample(CloudServerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_server
     *
     * @mbg.generated
     */
    CloudServer selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_server
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CloudServer record, @Param("example") CloudServerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_server
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CloudServer record, @Param("example") CloudServerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_server
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CloudServer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_server
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CloudServer record);
}