package com.fit2cloud.commons.server.base.mapper;

import com.fit2cloud.commons.server.base.domain.ExtraUser;
import com.fit2cloud.commons.server.base.domain.ExtraUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExtraUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table extra_user
     *
     * @mbg.generated
     */
    long countByExample(ExtraUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table extra_user
     *
     * @mbg.generated
     */
    int deleteByExample(ExtraUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table extra_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table extra_user
     *
     * @mbg.generated
     */
    int insert(ExtraUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table extra_user
     *
     * @mbg.generated
     */
    int insertSelective(ExtraUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table extra_user
     *
     * @mbg.generated
     */
    List<ExtraUser> selectByExample(ExtraUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table extra_user
     *
     * @mbg.generated
     */
    ExtraUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table extra_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ExtraUser record, @Param("example") ExtraUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table extra_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ExtraUser record, @Param("example") ExtraUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table extra_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ExtraUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table extra_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ExtraUser record);
}