package com.fit2cloud.commons.server.base.mapper;

import com.fit2cloud.commons.server.base.domain.FileStore;
import com.fit2cloud.commons.server.base.domain.FileStoreExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FileStoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_store
     *
     * @mbg.generated
     */
    long countByExample(FileStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_store
     *
     * @mbg.generated
     */
    int deleteByExample(FileStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_store
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_store
     *
     * @mbg.generated
     */
    int insert(FileStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_store
     *
     * @mbg.generated
     */
    int insertSelective(FileStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_store
     *
     * @mbg.generated
     */
    List<FileStore> selectByExampleWithBLOBs(FileStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_store
     *
     * @mbg.generated
     */
    List<FileStore> selectByExample(FileStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_store
     *
     * @mbg.generated
     */
    FileStore selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_store
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FileStore record, @Param("example") FileStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_store
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") FileStore record, @Param("example") FileStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_store
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FileStore record, @Param("example") FileStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_store
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FileStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_store
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(FileStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_store
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FileStore record);
}