package com.fit2cloud.commons.server.base.mapper;

import com.fit2cloud.commons.server.base.domain.FlowDeploy;
import com.fit2cloud.commons.server.base.domain.FlowDeployExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FlowDeployMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_deploy
     *
     * @mbg.generated
     */
    long countByExample(FlowDeployExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_deploy
     *
     * @mbg.generated
     */
    int deleteByExample(FlowDeployExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_deploy
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String deployId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_deploy
     *
     * @mbg.generated
     */
    int insert(FlowDeploy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_deploy
     *
     * @mbg.generated
     */
    int insertSelective(FlowDeploy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_deploy
     *
     * @mbg.generated
     */
    List<FlowDeploy> selectByExampleWithBLOBs(FlowDeployExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_deploy
     *
     * @mbg.generated
     */
    List<FlowDeploy> selectByExample(FlowDeployExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_deploy
     *
     * @mbg.generated
     */
    FlowDeploy selectByPrimaryKey(String deployId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_deploy
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FlowDeploy record, @Param("example") FlowDeployExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_deploy
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") FlowDeploy record, @Param("example") FlowDeployExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_deploy
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FlowDeploy record, @Param("example") FlowDeployExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_deploy
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FlowDeploy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_deploy
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(FlowDeploy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_deploy
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FlowDeploy record);
}