package com.fit2cloud.commons.server.base.mapper;

import com.fit2cloud.commons.server.base.domain.FlowTask;
import com.fit2cloud.commons.server.base.domain.FlowTaskExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FlowTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_task
     *
     * @mbg.generated
     */
    long countByExample(FlowTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_task
     *
     * @mbg.generated
     */
    int deleteByExample(FlowTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_task
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_task
     *
     * @mbg.generated
     */
    int insert(FlowTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_task
     *
     * @mbg.generated
     */
    int insertSelective(FlowTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_task
     *
     * @mbg.generated
     */
    List<FlowTask> selectByExampleWithBLOBs(FlowTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_task
     *
     * @mbg.generated
     */
    List<FlowTask> selectByExample(FlowTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_task
     *
     * @mbg.generated
     */
    FlowTask selectByPrimaryKey(String taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_task
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FlowTask record, @Param("example") FlowTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_task
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") FlowTask record, @Param("example") FlowTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_task
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FlowTask record, @Param("example") FlowTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_task
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FlowTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_task
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(FlowTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_task
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FlowTask record);
}