package com.fit2cloud.commons.server.base.mapper;

import com.fit2cloud.commons.server.base.domain.FlowModel;
import com.fit2cloud.commons.server.base.domain.FlowModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FlowModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_model
     *
     * @mbg.generated
     */
    long countByExample(FlowModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_model
     *
     * @mbg.generated
     */
    int deleteByExample(FlowModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_model
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String modelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_model
     *
     * @mbg.generated
     */
    int insert(FlowModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_model
     *
     * @mbg.generated
     */
    int insertSelective(FlowModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_model
     *
     * @mbg.generated
     */
    List<FlowModel> selectByExampleWithBLOBs(FlowModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_model
     *
     * @mbg.generated
     */
    List<FlowModel> selectByExample(FlowModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_model
     *
     * @mbg.generated
     */
    FlowModel selectByPrimaryKey(String modelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_model
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FlowModel record, @Param("example") FlowModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_model
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") FlowModel record, @Param("example") FlowModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_model
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FlowModel record, @Param("example") FlowModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_model
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FlowModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_model
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(FlowModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_model
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FlowModel record);
}