package com.fit2cloud.commons.server.base.mapper;

import com.fit2cloud.commons.server.base.domain.FlowLinkValue;
import com.fit2cloud.commons.server.base.domain.FlowLinkValueExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FlowLinkValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_link_value
     *
     * @mbg.generated
     */
    long countByExample(FlowLinkValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_link_value
     *
     * @mbg.generated
     */
    int deleteByExample(FlowLinkValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_link_value
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_link_value
     *
     * @mbg.generated
     */
    int insert(FlowLinkValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_link_value
     *
     * @mbg.generated
     */
    int insertSelective(FlowLinkValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_link_value
     *
     * @mbg.generated
     */
    List<FlowLinkValue> selectByExample(FlowLinkValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_link_value
     *
     * @mbg.generated
     */
    FlowLinkValue selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_link_value
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FlowLinkValue record, @Param("example") FlowLinkValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_link_value
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FlowLinkValue record, @Param("example") FlowLinkValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_link_value
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FlowLinkValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_link_value
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FlowLinkValue record);
}