package com.fit2cloud.commons.server.base.mapper;

import com.fit2cloud.commons.server.base.domain.FlowProcessData;
import com.fit2cloud.commons.server.base.domain.FlowProcessDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FlowProcessDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_process_data
     *
     * @mbg.generated
     */
    long countByExample(FlowProcessDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_process_data
     *
     * @mbg.generated
     */
    int deleteByExample(FlowProcessDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_process_data
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_process_data
     *
     * @mbg.generated
     */
    int insert(FlowProcessData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_process_data
     *
     * @mbg.generated
     */
    int insertSelective(FlowProcessData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_process_data
     *
     * @mbg.generated
     */
    List<FlowProcessData> selectByExampleWithBLOBs(FlowProcessDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_process_data
     *
     * @mbg.generated
     */
    List<FlowProcessData> selectByExample(FlowProcessDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_process_data
     *
     * @mbg.generated
     */
    FlowProcessData selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_process_data
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FlowProcessData record, @Param("example") FlowProcessDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_process_data
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") FlowProcessData record, @Param("example") FlowProcessDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_process_data
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FlowProcessData record, @Param("example") FlowProcessDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_process_data
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FlowProcessData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_process_data
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(FlowProcessData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_process_data
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FlowProcessData record);
}