package com.fit2cloud.commons.server.base.mapper;

import com.fit2cloud.commons.server.base.domain.FlowProcessLog;
import com.fit2cloud.commons.server.base.domain.FlowProcessLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FlowProcessLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_process_log
     *
     * @mbg.generated
     */
    long countByExample(FlowProcessLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_process_log
     *
     * @mbg.generated
     */
    int deleteByExample(FlowProcessLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_process_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_process_log
     *
     * @mbg.generated
     */
    int insert(FlowProcessLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_process_log
     *
     * @mbg.generated
     */
    int insertSelective(FlowProcessLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_process_log
     *
     * @mbg.generated
     */
    List<FlowProcessLog> selectByExampleWithBLOBs(FlowProcessLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_process_log
     *
     * @mbg.generated
     */
    List<FlowProcessLog> selectByExample(FlowProcessLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_process_log
     *
     * @mbg.generated
     */
    FlowProcessLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_process_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FlowProcessLog record, @Param("example") FlowProcessLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_process_log
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") FlowProcessLog record, @Param("example") FlowProcessLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_process_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FlowProcessLog record, @Param("example") FlowProcessLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_process_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FlowProcessLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_process_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(FlowProcessLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_process_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FlowProcessLog record);
}