package com.fit2cloud.commons.server.base.mapper;

import com.fit2cloud.commons.server.base.domain.FlowRole;
import com.fit2cloud.commons.server.base.domain.FlowRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FlowRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_role
     *
     * @mbg.generated
     */
    long countByExample(FlowRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_role
     *
     * @mbg.generated
     */
    int deleteByExample(FlowRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String roleKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_role
     *
     * @mbg.generated
     */
    int insert(FlowRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_role
     *
     * @mbg.generated
     */
    int insertSelective(FlowRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_role
     *
     * @mbg.generated
     */
    List<FlowRole> selectByExample(FlowRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_role
     *
     * @mbg.generated
     */
    FlowRole selectByPrimaryKey(String roleKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FlowRole record, @Param("example") FlowRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FlowRole record, @Param("example") FlowRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FlowRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FlowRole record);
}