package com.fit2cloud.commons.server.base.mapper;

import com.fit2cloud.commons.server.base.domain.FlowProcess;
import com.fit2cloud.commons.server.base.domain.FlowProcessExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FlowProcessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_process
     *
     * @mbg.generated
     */
    long countByExample(FlowProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_process
     *
     * @mbg.generated
     */
    int deleteByExample(FlowProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_process
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String processId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_process
     *
     * @mbg.generated
     */
    int insert(FlowProcess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_process
     *
     * @mbg.generated
     */
    int insertSelective(FlowProcess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_process
     *
     * @mbg.generated
     */
    List<FlowProcess> selectByExample(FlowProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_process
     *
     * @mbg.generated
     */
    FlowProcess selectByPrimaryKey(String processId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_process
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FlowProcess record, @Param("example") FlowProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_process
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FlowProcess record, @Param("example") FlowProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_process
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FlowProcess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_process
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FlowProcess record);
}