package com.fit2cloud.commons.server.base.mapper;

import com.fit2cloud.commons.server.base.domain.FlowNotificationConfig;
import com.fit2cloud.commons.server.base.domain.FlowNotificationConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FlowNotificationConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_notification_config
     *
     * @mbg.generated
     */
    long countByExample(FlowNotificationConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_notification_config
     *
     * @mbg.generated
     */
    int deleteByExample(FlowNotificationConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_notification_config
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_notification_config
     *
     * @mbg.generated
     */
    int insert(FlowNotificationConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_notification_config
     *
     * @mbg.generated
     */
    int insertSelective(FlowNotificationConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_notification_config
     *
     * @mbg.generated
     */
    List<FlowNotificationConfig> selectByExampleWithBLOBs(FlowNotificationConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_notification_config
     *
     * @mbg.generated
     */
    List<FlowNotificationConfig> selectByExample(FlowNotificationConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_notification_config
     *
     * @mbg.generated
     */
    FlowNotificationConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_notification_config
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FlowNotificationConfig record, @Param("example") FlowNotificationConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_notification_config
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") FlowNotificationConfig record, @Param("example") FlowNotificationConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_notification_config
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FlowNotificationConfig record, @Param("example") FlowNotificationConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_notification_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FlowNotificationConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_notification_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(FlowNotificationConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_notification_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FlowNotificationConfig record);
}