package com.fit2cloud.commons.server.base.mapper;

import com.fit2cloud.commons.server.base.domain.FlowLinkValueScope;
import com.fit2cloud.commons.server.base.domain.FlowLinkValueScopeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FlowLinkValueScopeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_link_value_scope
     *
     * @mbg.generated
     */
    long countByExample(FlowLinkValueScopeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_link_value_scope
     *
     * @mbg.generated
     */
    int deleteByExample(FlowLinkValueScopeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_link_value_scope
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_link_value_scope
     *
     * @mbg.generated
     */
    int insert(FlowLinkValueScope record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_link_value_scope
     *
     * @mbg.generated
     */
    int insertSelective(FlowLinkValueScope record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_link_value_scope
     *
     * @mbg.generated
     */
    List<FlowLinkValueScope> selectByExample(FlowLinkValueScopeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_link_value_scope
     *
     * @mbg.generated
     */
    FlowLinkValueScope selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_link_value_scope
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FlowLinkValueScope record, @Param("example") FlowLinkValueScopeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_link_value_scope
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FlowLinkValueScope record, @Param("example") FlowLinkValueScopeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_link_value_scope
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FlowLinkValueScope record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_link_value_scope
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FlowLinkValueScope record);
}