package com.fit2cloud.commons.server.base.mapper;

import com.fit2cloud.commons.server.base.domain.FlowEvent;
import com.fit2cloud.commons.server.base.domain.FlowEventExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FlowEventMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_event
     *
     * @mbg.generated
     */
    long countByExample(FlowEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_event
     *
     * @mbg.generated
     */
    int deleteByExample(FlowEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_event
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_event
     *
     * @mbg.generated
     */
    int insert(FlowEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_event
     *
     * @mbg.generated
     */
    int insertSelective(FlowEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_event
     *
     * @mbg.generated
     */
    List<FlowEvent> selectByExampleWithBLOBs(FlowEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_event
     *
     * @mbg.generated
     */
    List<FlowEvent> selectByExample(FlowEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_event
     *
     * @mbg.generated
     */
    FlowEvent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_event
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FlowEvent record, @Param("example") FlowEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_event
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") FlowEvent record, @Param("example") FlowEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_event
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FlowEvent record, @Param("example") FlowEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_event
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FlowEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_event
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(FlowEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_event
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FlowEvent record);
}