package com.fit2cloud.commons.server.base.mapper;

import com.fit2cloud.commons.server.base.domain.FlowLink;
import com.fit2cloud.commons.server.base.domain.FlowLinkExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FlowLinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_link
     *
     * @mbg.generated
     */
    long countByExample(FlowLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_link
     *
     * @mbg.generated
     */
    int deleteByExample(FlowLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_link
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String linkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_link
     *
     * @mbg.generated
     */
    int insert(FlowLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_link
     *
     * @mbg.generated
     */
    int insertSelective(FlowLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_link
     *
     * @mbg.generated
     */
    List<FlowLink> selectByExample(FlowLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_link
     *
     * @mbg.generated
     */
    FlowLink selectByPrimaryKey(String linkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_link
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FlowLink record, @Param("example") FlowLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_link
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FlowLink record, @Param("example") FlowLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_link
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FlowLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_link
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FlowLink record);
}