package com.fit2cloud.commons.server.base.mapper;

import com.fit2cloud.commons.server.base.domain.FlowNotificationInbox;
import com.fit2cloud.commons.server.base.domain.FlowNotificationInboxExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FlowNotificationInboxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_notification_inbox
     *
     * @mbg.generated
     */
    long countByExample(FlowNotificationInboxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_notification_inbox
     *
     * @mbg.generated
     */
    int deleteByExample(FlowNotificationInboxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_notification_inbox
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_notification_inbox
     *
     * @mbg.generated
     */
    int insert(FlowNotificationInbox record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_notification_inbox
     *
     * @mbg.generated
     */
    int insertSelective(FlowNotificationInbox record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_notification_inbox
     *
     * @mbg.generated
     */
    List<FlowNotificationInbox> selectByExampleWithBLOBs(FlowNotificationInboxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_notification_inbox
     *
     * @mbg.generated
     */
    List<FlowNotificationInbox> selectByExample(FlowNotificationInboxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_notification_inbox
     *
     * @mbg.generated
     */
    FlowNotificationInbox selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_notification_inbox
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FlowNotificationInbox record, @Param("example") FlowNotificationInboxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_notification_inbox
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") FlowNotificationInbox record, @Param("example") FlowNotificationInboxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_notification_inbox
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FlowNotificationInbox record, @Param("example") FlowNotificationInboxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_notification_inbox
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FlowNotificationInbox record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_notification_inbox
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(FlowNotificationInbox record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_notification_inbox
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FlowNotificationInbox record);
}