package com.fit2cloud.commons.server.base.mapper;

import com.fit2cloud.commons.server.base.domain.FlowRoleUser;
import com.fit2cloud.commons.server.base.domain.FlowRoleUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FlowRoleUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_role_user
     *
     * @mbg.generated
     */
    long countByExample(FlowRoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_role_user
     *
     * @mbg.generated
     */
    int deleteByExample(FlowRoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_role_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_role_user
     *
     * @mbg.generated
     */
    int insert(FlowRoleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_role_user
     *
     * @mbg.generated
     */
    int insertSelective(FlowRoleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_role_user
     *
     * @mbg.generated
     */
    List<FlowRoleUser> selectByExample(FlowRoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_role_user
     *
     * @mbg.generated
     */
    FlowRoleUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_role_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FlowRoleUser record, @Param("example") FlowRoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_role_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FlowRoleUser record, @Param("example") FlowRoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_role_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FlowRoleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_role_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FlowRoleUser record);
}