package com.fit2cloud.commons.server.base.mapper;

import com.fit2cloud.commons.server.base.domain.I18n;
import com.fit2cloud.commons.server.base.domain.I18nExample;
import com.fit2cloud.commons.server.base.domain.I18nWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface I18nMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i18n
     *
     * @mbg.generated
     */
    long countByExample(I18nExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i18n
     *
     * @mbg.generated
     */
    int deleteByExample(I18nExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i18n
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i18n
     *
     * @mbg.generated
     */
    int insert(I18nWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i18n
     *
     * @mbg.generated
     */
    int insertSelective(I18nWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i18n
     *
     * @mbg.generated
     */
    List<I18nWithBLOBs> selectByExampleWithBLOBs(I18nExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i18n
     *
     * @mbg.generated
     */
    List<I18n> selectByExample(I18nExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i18n
     *
     * @mbg.generated
     */
    I18nWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i18n
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") I18nWithBLOBs record, @Param("example") I18nExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i18n
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") I18nWithBLOBs record, @Param("example") I18nExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i18n
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") I18n record, @Param("example") I18nExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i18n
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(I18nWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i18n
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(I18nWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i18n
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(I18n record);
}