package com.fit2cloud.commons.server.base.mapper;

import com.fit2cloud.commons.server.base.domain.MenuPreference;
import com.fit2cloud.commons.server.base.domain.MenuPreferenceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MenuPreferenceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_preference
     *
     * @mbg.generated
     */
    long countByExample(MenuPreferenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_preference
     *
     * @mbg.generated
     */
    int deleteByExample(MenuPreferenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_preference
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_preference
     *
     * @mbg.generated
     */
    int insert(MenuPreference record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_preference
     *
     * @mbg.generated
     */
    int insertSelective(MenuPreference record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_preference
     *
     * @mbg.generated
     */
    List<MenuPreference> selectByExample(MenuPreferenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_preference
     *
     * @mbg.generated
     */
    MenuPreference selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_preference
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MenuPreference record, @Param("example") MenuPreferenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_preference
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MenuPreference record, @Param("example") MenuPreferenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_preference
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MenuPreference record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_preference
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MenuPreference record);
}