package com.fit2cloud.commons.server.base.mapper;

import com.fit2cloud.commons.server.base.domain.ModulePermission;
import com.fit2cloud.commons.server.base.domain.ModulePermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ModulePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_permission
     *
     * @mbg.generated
     */
    long countByExample(ModulePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_permission
     *
     * @mbg.generated
     */
    int deleteByExample(ModulePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_permission
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_permission
     *
     * @mbg.generated
     */
    int insert(ModulePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_permission
     *
     * @mbg.generated
     */
    int insertSelective(ModulePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_permission
     *
     * @mbg.generated
     */
    List<ModulePermission> selectByExample(ModulePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_permission
     *
     * @mbg.generated
     */
    ModulePermission selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_permission
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ModulePermission record, @Param("example") ModulePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_permission
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ModulePermission record, @Param("example") ModulePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ModulePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ModulePermission record);
}