package com.fit2cloud.commons.server.base.mapper;

import com.fit2cloud.commons.server.base.domain.NetworkTag;
import com.fit2cloud.commons.server.base.domain.NetworkTagExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NetworkTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table network_tag
     *
     * @mbg.generated
     */
    long countByExample(NetworkTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table network_tag
     *
     * @mbg.generated
     */
    int deleteByExample(NetworkTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table network_tag
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table network_tag
     *
     * @mbg.generated
     */
    int insert(NetworkTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table network_tag
     *
     * @mbg.generated
     */
    int insertSelective(NetworkTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table network_tag
     *
     * @mbg.generated
     */
    List<NetworkTag> selectByExample(NetworkTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table network_tag
     *
     * @mbg.generated
     */
    NetworkTag selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table network_tag
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") NetworkTag record, @Param("example") NetworkTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table network_tag
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") NetworkTag record, @Param("example") NetworkTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table network_tag
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(NetworkTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table network_tag
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(NetworkTag record);
}