package com.fit2cloud.commons.server.base.mapper;

import com.fit2cloud.commons.server.base.domain.NetworkTagMapping;
import com.fit2cloud.commons.server.base.domain.NetworkTagMappingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NetworkTagMappingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table network_tag_mapping
     *
     * @mbg.generated
     */
    long countByExample(NetworkTagMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table network_tag_mapping
     *
     * @mbg.generated
     */
    int deleteByExample(NetworkTagMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table network_tag_mapping
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table network_tag_mapping
     *
     * @mbg.generated
     */
    int insert(NetworkTagMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table network_tag_mapping
     *
     * @mbg.generated
     */
    int insertSelective(NetworkTagMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table network_tag_mapping
     *
     * @mbg.generated
     */
    List<NetworkTagMapping> selectByExample(NetworkTagMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table network_tag_mapping
     *
     * @mbg.generated
     */
    NetworkTagMapping selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table network_tag_mapping
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") NetworkTagMapping record, @Param("example") NetworkTagMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table network_tag_mapping
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") NetworkTagMapping record, @Param("example") NetworkTagMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table network_tag_mapping
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(NetworkTagMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table network_tag_mapping
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(NetworkTagMapping record);
}