package com.fit2cloud.commons.server.base.mapper;

import com.fit2cloud.commons.server.base.domain.ProxyResource;
import com.fit2cloud.commons.server.base.domain.ProxyResourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProxyResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxy_resource
     *
     * @mbg.generated
     */
    long countByExample(ProxyResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxy_resource
     *
     * @mbg.generated
     */
    int deleteByExample(ProxyResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxy_resource
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxy_resource
     *
     * @mbg.generated
     */
    int insert(ProxyResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxy_resource
     *
     * @mbg.generated
     */
    int insertSelective(ProxyResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxy_resource
     *
     * @mbg.generated
     */
    List<ProxyResource> selectByExample(ProxyResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxy_resource
     *
     * @mbg.generated
     */
    ProxyResource selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxy_resource
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ProxyResource record, @Param("example") ProxyResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxy_resource
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ProxyResource record, @Param("example") ProxyResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxy_resource
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProxyResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxy_resource
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProxyResource record);
}