package com.fit2cloud.commons.server.base.mapper;

import com.fit2cloud.commons.server.base.domain.SystemParameter;
import com.fit2cloud.commons.server.base.domain.SystemParameterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SystemParameterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_parameter
     *
     * @mbg.generated
     */
    long countByExample(SystemParameterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_parameter
     *
     * @mbg.generated
     */
    int deleteByExample(SystemParameterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_parameter
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String paramKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_parameter
     *
     * @mbg.generated
     */
    int insert(SystemParameter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_parameter
     *
     * @mbg.generated
     */
    int insertSelective(SystemParameter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_parameter
     *
     * @mbg.generated
     */
    List<SystemParameter> selectByExample(SystemParameterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_parameter
     *
     * @mbg.generated
     */
    SystemParameter selectByPrimaryKey(String paramKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_parameter
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SystemParameter record, @Param("example") SystemParameterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_parameter
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SystemParameter record, @Param("example") SystemParameterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_parameter
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SystemParameter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_parameter
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SystemParameter record);
}