package com.fit2cloud.commons.server.base.mapper;

import com.fit2cloud.commons.server.base.domain.TagMapping;
import com.fit2cloud.commons.server.base.domain.TagMappingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TagMappingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_mapping
     *
     * @mbg.generated
     */
    long countByExample(TagMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_mapping
     *
     * @mbg.generated
     */
    int deleteByExample(TagMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_mapping
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_mapping
     *
     * @mbg.generated
     */
    int insert(TagMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_mapping
     *
     * @mbg.generated
     */
    int insertSelective(TagMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_mapping
     *
     * @mbg.generated
     */
    List<TagMapping> selectByExample(TagMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_mapping
     *
     * @mbg.generated
     */
    TagMapping selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_mapping
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TagMapping record, @Param("example") TagMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_mapping
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TagMapping record, @Param("example") TagMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_mapping
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TagMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_mapping
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TagMapping record);
}