package com.fit2cloud.commons.server.base.mapper;

import com.fit2cloud.commons.server.base.domain.TagValue;
import com.fit2cloud.commons.server.base.domain.TagValueExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TagValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_value
     *
     * @mbg.generated
     */
    long countByExample(TagValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_value
     *
     * @mbg.generated
     */
    int deleteByExample(TagValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_value
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_value
     *
     * @mbg.generated
     */
    int insert(TagValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_value
     *
     * @mbg.generated
     */
    int insertSelective(TagValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_value
     *
     * @mbg.generated
     */
    List<TagValue> selectByExample(TagValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_value
     *
     * @mbg.generated
     */
    TagValue selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_value
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TagValue record, @Param("example") TagValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_value
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TagValue record, @Param("example") TagValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_value
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TagValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_value
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TagValue record);
}