package com.fit2cloud.commons.server.base.mapper;

import com.fit2cloud.commons.server.base.domain.UserKey;
import com.fit2cloud.commons.server.base.domain.UserKeyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserKeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_key
     *
     * @mbg.generated
     */
    long countByExample(UserKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_key
     *
     * @mbg.generated
     */
    int deleteByExample(UserKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_key
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_key
     *
     * @mbg.generated
     */
    int insert(UserKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_key
     *
     * @mbg.generated
     */
    int insertSelective(UserKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_key
     *
     * @mbg.generated
     */
    List<UserKey> selectByExample(UserKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_key
     *
     * @mbg.generated
     */
    UserKey selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_key
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserKey record, @Param("example") UserKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_key
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserKey record, @Param("example") UserKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_key
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_key
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserKey record);
}