package com.fit2cloud.commons.server.base.mapper;

import com.fit2cloud.commons.server.base.domain.Workspace;
import com.fit2cloud.commons.server.base.domain.WorkspaceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WorkspaceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workspace
     *
     * @mbg.generated
     */
    long countByExample(WorkspaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workspace
     *
     * @mbg.generated
     */
    int deleteByExample(WorkspaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workspace
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workspace
     *
     * @mbg.generated
     */
    int insert(Workspace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workspace
     *
     * @mbg.generated
     */
    int insertSelective(Workspace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workspace
     *
     * @mbg.generated
     */
    List<Workspace> selectByExample(WorkspaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workspace
     *
     * @mbg.generated
     */
    Workspace selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workspace
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Workspace record, @Param("example") WorkspaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workspace
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Workspace record, @Param("example") WorkspaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workspace
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Workspace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workspace
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Workspace record);
}