package com.fit2cloud.sdk.model;

public enum  F2CEntityType {
    // VMware
    DATACENTER, CLUSTER, HOSTSYSTEM, VIRTUALMACHINE, IMAGE, DATASTORE, STORAGEPOD, DISK,
    CLUSTERCOMPUTERESOURCE, FOLDER, RESOURCEPOOL, COMPUTERESOURCE,
    // ZStack
    BACKUPSTORAGE, VOLUME, VCENTER, SYSTEM, HOST, VIP, PRIMARYSTORAGE, VM, L3NETWORK, LICENSE, LOADBALANCER, MN
    // FusionCompute
    ,SITES,VRMS
}
