insert into `dictionary` ( `id`, `category`, `dictionary_key`, `dictionary_value`, `long_value`, `description`, `dictionary_time`) values ( '0c9c8d21-5859-4210-b83b-3f7813cf056d', 'vm_os_version', 'ubuntu', '16.04', null, null, null);
insert into `dictionary` ( `id`, `category`, `dictionary_key`, `dictionary_value`, `long_value`, `description`, `dictionary_time`) values ( '173622d4-61f9-4b29-b4c8-dbc5533f6440', 'vm_os_version', 'ubuntu', '14.04', null, null, null);
insert into `dictionary` ( `id`, `category`, `dictionary_key`, `dictionary_value`, `long_value`, `description`, `dictionary_time`) values ( '1c59d32c-d7f1-498f-8240-154587e6e7b0', 'vm_os_version', 'redhat', '5', null, null, null);
insert into `dictionary` ( `id`, `category`, `dictionary_key`, `dictionary_value`, `long_value`, `description`, `dictionary_time`) values ( '21c3d374-bd28-473c-8ced-231af07f070f', 'vm_os_version', 'windows', '2008 ', null, null, null);
insert into `dictionary` ( `id`, `category`, `dictionary_key`, `dictionary_value`, `long_value`, `description`, `dictionary_time`) values ( '21fbf8a4-d43f-4af4-b246-b02879f72077', 'vm_os_version', 'ubuntu', '18.04', null, null, null);
insert into `dictionary` ( `id`, `category`, `dictionary_key`, `dictionary_value`, `long_value`, `description`, `dictionary_time`) values ( '31d52afa-5a77-4892-ba5a-b15f2026f93b', 'vm_os_version', 'ubuntu', '10.04', null, null, null);
insert into `dictionary` ( `id`, `category`, `dictionary_key`, `dictionary_value`, `long_value`, `description`, `dictionary_time`) values ( '4010eb98-2d82-4868-b9ae-34907fa5d79c', 'vm_os_version', 'redhat', '6', null, null, null);
insert into `dictionary` ( `id`, `category`, `dictionary_key`, `dictionary_value`, `long_value`, `description`, `dictionary_time`) values ( '4206ef3e-5cc7-4bd7-9f6f-acbec8eafe79', 'vm_os', 'windows', 'Windows Server  64-bit', null, null, null);
insert into `dictionary` ( `id`, `category`, `dictionary_key`, `dictionary_value`, `long_value`, `description`, `dictionary_time`) values ( '535afe28-ef9b-4bcc-a6d7-91a27d73e552', 'vm_os', 'centos', 'CentOS  64-bit', null, null, null);
insert into `dictionary` ( `id`, `category`, `dictionary_key`, `dictionary_value`, `long_value`, `description`, `dictionary_time`) values ( '56b9bfe2-07d8-4a76-8074-6f07c9298a87', 'vm_os_version', 'redhat', '7', null, null, null);
insert into `dictionary` ( `id`, `category`, `dictionary_key`, `dictionary_value`, `long_value`, `description`, `dictionary_time`) values ( '5e4fa747-8d13-4125-9a40-c65670e87740', 'vm_os', 'ubuntu', 'Ubuntu Server  64-bit', null, null, null);
insert into `dictionary` ( `id`, `category`, `dictionary_key`, `dictionary_value`, `long_value`, `description`, `dictionary_time`) values ( '6038d01f-1be5-4a26-9806-a750c0584134', 'vm_os_version', 'windows', '2008 R2', null, null, null);
insert into `dictionary` ( `id`, `category`, `dictionary_key`, `dictionary_value`, `long_value`, `description`, `dictionary_time`) values ( '61f5789b-2562-480d-aff2-443449678bed', 'vm_os_version', 'centos', '6', null, null, null);
insert into `dictionary` ( `id`, `category`, `dictionary_key`, `dictionary_value`, `long_value`, `description`, `dictionary_time`) values ( '682c2e91-63e3-4104-8c11-dc7c60457e9f', 'vm_os', 'suse', 'SUSE Linux Enterprise  64-bit', null, null, null);
insert into `dictionary` ( `id`, `category`, `dictionary_key`, `dictionary_value`, `long_value`, `description`, `dictionary_time`) values ( '69f5ae2d-d995-4e07-b9d6-5d5c13a6a2ea', 'vm_os_version', 'windows', '2012', null, null, null);
insert into `dictionary` ( `id`, `category`, `dictionary_key`, `dictionary_value`, `long_value`, `description`, `dictionary_time`) values ( '6cfc9784-390d-4a7b-a6df-5d3eb3a25bb9', 'vm_os_version', 'suse', '15', null, null, null);
insert into `dictionary` ( `id`, `category`, `dictionary_key`, `dictionary_value`, `long_value`, `description`, `dictionary_time`) values ( '70c06d27-e40b-471a-8150-1e4b56ceebae', 'vm_os_version', 'suse', '10', null, null, null);
insert into `dictionary` ( `id`, `category`, `dictionary_key`, `dictionary_value`, `long_value`, `description`, `dictionary_time`) values ( '70d2a8df-f8c6-4f55-aead-0501a4e8c175', 'vm_os_version', 'suse', '12', null, null, null);
insert into `dictionary` ( `id`, `category`, `dictionary_key`, `dictionary_value`, `long_value`, `description`, `dictionary_time`) values ( '7abbcf9d-5203-4054-ad53-6990f649714a', 'vm_os_version', 'windows', '2019', null, null, null);
insert into `dictionary` ( `id`, `category`, `dictionary_key`, `dictionary_value`, `long_value`, `description`, `dictionary_time`) values ( '8746ed29-2b70-459d-bb3e-42dd99ec6483', 'vm_os_version', 'windows', '2003', null, null, null);
insert into `dictionary` ( `id`, `category`, `dictionary_key`, `dictionary_value`, `long_value`, `description`, `dictionary_time`) values ( '90d6012a-be9a-440f-8969-18e40c46f73b', 'vm_os_version', 'centos', '5', null, null, null);
insert into `dictionary` ( `id`, `category`, `dictionary_key`, `dictionary_value`, `long_value`, `description`, `dictionary_time`) values ( '9a37fdd7-9b0a-4358-aa88-873c8da72633', 'vm_os_version', 'windows', '2003 R2', null, null, null);
insert into `dictionary` ( `id`, `category`, `dictionary_key`, `dictionary_value`, `long_value`, `description`, `dictionary_time`) values ( 'a0295f1b-6639-44a9-b5ed-c5df8a41dcb1', 'vm_os_version', 'suse', '11', null, null, null);
insert into `dictionary` ( `id`, `category`, `dictionary_key`, `dictionary_value`, `long_value`, `description`, `dictionary_time`) values ( 'a46e04d7-0113-4110-9867-af7884e36600', 'vm_os_version', 'windows', '2012 R2', null, null, null);
insert into `dictionary` ( `id`, `category`, `dictionary_key`, `dictionary_value`, `long_value`, `description`, `dictionary_time`) values ( 'd4fada1a-d566-4925-ad92-cf46f4dd1637', 'vm_os_version', 'ubuntu', '12.04', null, null, null);
insert into `dictionary` ( `id`, `category`, `dictionary_key`, `dictionary_value`, `long_value`, `description`, `dictionary_time`) values ( 'db6c88f4-ad6b-48bb-be81-4eb6648a9892', 'vm_os', 'redhat', 'Red Hat Enterprise Linux 64-bit', null, null, null);
insert into `dictionary` ( `id`, `category`, `dictionary_key`, `dictionary_value`, `long_value`, `description`, `dictionary_time`) values ( 'dbf3f60e-94e5-4539-8009-7b8009b2a513', 'vm_os_version', 'windows', '2016', null, null, null);
insert into `dictionary` ( `id`, `category`, `dictionary_key`, `dictionary_value`, `long_value`, `description`, `dictionary_time`) values ( 'ee5d0549-b7a8-4f93-b844-60a7f239ff5c', 'vm_os_version', 'centos', '7', null, null, null);

insert into `role` ( `id`, `name`, `description`, `type`, `parent_id`) values ( 'ADMIN', '系统管理员', '系统管理员', 'System', 'ADMIN');
insert into `role` ( `id`, `name`, `description`, `type`, `parent_id`) values ( 'ORGADMIN', '组织管理员', '组织管理员', 'System', 'ORGADMIN');
insert into `role` ( `id`, `name`, `description`, `type`, `parent_id`) values ( 'USER', '工作空间用户', '工作空间用户', 'System', 'USER');

insert into `user` ( `id`, `name`, `email`, `source`, `password`, `active`, `phone`, `create_time`, `last_source_id`) values ( 'admin', '管理员', 'admin@fit2cloud.com', 'local', '5b2f13d1b260f80a9dae48e94d9f6486', '1', '', '1537330192693', 'admin');

insert into `user_role` ( `id`, `user_id`, `role_id`, `source_id`) values ( 'daa19706-d730-4e6d-854f-a828c50d6637', 'admin', 'ADMIN', null);

INSERT INTO  `plugin` (`id`, `name`, `description`, `version`, `owner`, `status`, `current_file`, `plugin_type`, `icon`, `update_time`) VALUES ('1', 'fit2cloud-vsphere-plugin', 'VMware vSphere', '3.0', 'FIT2CLOUD', 'available', '/opt/fit2cloud/plugins/fit2cloud-vsphere-plugin-2.0-jar-with-dependencies.jar', 'infrastructure', 'web-public/fit2cloud/img/cloud-vendor-icon/vmware.ico', '1533052800000');
INSERT INTO  `plugin` (`id`, `name`, `description`, `version`, `owner`, `status`, `current_file`, `plugin_type`, `icon`, `update_time`) VALUES ('10', 'fit2cloud-qingcloud-plugin', '青云', '3.0', 'FIT2CLOUD', 'available', '/opt/fit2cloud/plugins/fit2cloud-qingcloud-plugin-2.0-jar-with-dependencies.jar', 'infrastructure', 'web-public/fit2cloud/img/cloud-vendor-icon/qingyun.ico', '1533052800000');
INSERT INTO  `plugin` (`id`, `name`, `description`, `version`, `owner`, `status`, `current_file`, `plugin_type`, `icon`, `update_time`) VALUES ('11', 'fit2cloud-huawei-plugin', '华为公有云', '3.0', 'FIT2CLOUD', 'available', '/opt/fit2cloud/plugins/fit2cloud-huawei-plugin-2.0-jar-with-dependencies.jar', 'infrastructure', 'web-public/fit2cloud/img/cloud-vendor-icon/fusion.ico', '1533052800000');
INSERT INTO  `plugin` (`id`, `name`, `description`, `version`, `owner`, `status`, `current_file`, `plugin_type`, `icon`, `update_time`) VALUES ('12', 'fit2cloud-fusionsphere-huawei-openstack-plugin', '华为私有云', '3.0', 'FIT2CLOUD', 'available', '/opt/fit2cloud/plugins/fit2cloud-fusionsphere-huawei-openstack-plugin-2.0-jar-with-dependencies.jar', 'infrastructure', 'web-public/fit2cloud/img/cloud-vendor-icon/fusion.ico', '1533052800000');
INSERT INTO  `plugin` (`id`, `name`, `description`, `version`, `owner`, `status`, `current_file`, `plugin_type`, `icon`, `update_time`) VALUES ('13', 'fit2cloud-ksyun-plugin', 'Ksyun', '3.0', 'FIT2CLOUD', 'available', 'fit2cloud-ksyun-plugin-2.0-jar-with-dependencies.jar', 'infrastructure', 'web-public/fit2cloud/img/cloud-vendor-icon/ksyun.ico', '1533052800000');
INSERT INTO  `plugin` (`id`, `name`, `description`, `version`, `owner`, `status`, `current_file`, `plugin_type`, `icon`, `update_time`) VALUES ('14', 'fit2cloud-baidu-plugin', '百度云', '3.0', 'FIT2CLOUD', 'available', '/opt/fit2cloud/plugins/fit2cloud-baidu-plugin-2.0-jar-with-dependencies.jar', 'infrastructure', 'web-public/fit2cloud/img/cloud-vendor-icon/baiduyun.ico', '1533052800000');
INSERT INTO  `plugin` (`id`, `name`, `description`, `version`, `owner`, `status`, `current_file`, `plugin_type`, `icon`, `update_time`) VALUES ('15', 'fit2cloud-zstack-plugin', 'ZStack', '3.0', 'FIT2CLOUD', 'available', '/opt/fit2cloud/plugins/fit2cloud-zstack-plugin-2.0-jar-with-dependencies.jar', 'infrastructure', 'web-public/fit2cloud/img/cloud-vendor-icon/zstack.png', '1533052800000');
INSERT INTO  `plugin` (`id`, `name`, `description`, `version`, `owner`, `status`, `current_file`, `plugin_type`, `icon`, `update_time`) VALUES ('16', 'fit2cloud-fusioncompute-plugin', '华为 FusionCompute', '3.0', 'FIT2CLOUD', 'available', '/opt/fit2cloud/plugins/fit2cloud-fusioncompute-plugin-2.0-jar-with-dependencies.jar', 'infrastructure', 'web-public/fit2cloud/img/cloud-vendor-icon/fusion.ico', '1533052800000');
INSERT INTO  `plugin` (`id`, `name`, `description`, `version`, `owner`, `status`, `current_file`, `plugin_type`, `icon`, `update_time`) VALUES ('2', 'fit2cloud-aws-plugin', 'Amazon Web Services', '3.0', 'FIT2CLOUD', 'available', '/opt/fit2cloud/plugins/fit2cloud-aws-plugin-2.0-jar-with-dependencies.jar', 'infrastructure', 'web-public/fit2cloud/img/cloud-vendor-icon/aws.ico', '1533052800000');
INSERT INTO  `plugin` (`id`, `name`, `description`, `version`, `owner`, `status`, `current_file`, `plugin_type`, `icon`, `update_time`) VALUES ('3', 'fit2cloud-azure-plugin', 'Microsoft Azure', '3.0', 'FIT2CLOUD', 'available', '/opt/fit2cloud/plugins/fit2cloud-azure-plugin-2.0-jar-with-dependencies.jar', 'infrastructure', 'web-public/fit2cloud/img/cloud-vendor-icon/azure.ico', '1533052800000');
INSERT INTO  `plugin` (`id`, `name`, `description`, `version`, `owner`, `status`, `current_file`, `plugin_type`, `icon`, `update_time`) VALUES ('4', 'fit2cloud-openstack-plugin', 'OpenStack', '3.0', 'FIT2CLOUD', 'available', '/opt/fit2cloud/plugins/fit2cloud-openstack-plugin-2.0-jar-with-dependencies.jar', 'infrastructure', 'web-public/fit2cloud/img/cloud-vendor-icon/openstack.ico', '1533052800000');
INSERT INTO  `plugin` (`id`, `name`, `description`, `version`, `owner`, `status`, `current_file`, `plugin_type`, `icon`, `update_time`) VALUES ('5', 'fit2cloud-nutanix-plugin', 'Nutanix', '3.0', 'FIT2CLOUD', 'available', '/opt/fit2cloud/plugins/fit2cloud-nutanix-plugin-2.0-jar-with-dependencies.jar', 'infrastructure', 'web-public/fit2cloud/img/cloud-vendor-icon/nutanix.ico', '1533052800000');
INSERT INTO  `plugin` (`id`, `name`, `description`, `version`, `owner`, `status`, `current_file`, `plugin_type`, `icon`, `update_time`) VALUES ('6', 'fit2cloud-qcloud-plugin', '腾讯云', '3.0', 'FIT2CLOUD', 'available', '/opt/fit2cloud/plugins/fit2cloud-qcloud-plugin-2.0-jar-with-dependencies.jar', 'infrastructure', 'web-public/fit2cloud/img/cloud-vendor-icon/qcloud.ico', '1533052800000');
INSERT INTO  `plugin` (`id`, `name`, `description`, `version`, `owner`, `status`, `current_file`, `plugin_type`, `icon`, `update_time`) VALUES ('7', 'fit2cloud-aliyun-plugin', '阿里云', '3.0', 'FIT2CLOUD', 'available', '/opt/fit2cloud/plugins/fit2cloud-aliyun-plugin-2.0-jar-with-dependencies.jar', 'infrastructure', 'web-public/fit2cloud/img/cloud-vendor-icon/aliyun.ico', '1533052800000');
INSERT INTO  `plugin` (`id`, `name`, `description`, `version`, `owner`, `status`, `current_file`, `plugin_type`, `icon`, `update_time`) VALUES ('8', 'fit2cloud-openshift-plugin', 'OpenShift', '3.0', 'FIT2CLOUD', 'available', '/opt/fit2cloud/plugins/openshift-plugin-2.0-jar-with-dependencies.jar', 'container', 'web-public/fit2cloud/img/cloud-vendor-icon/openshift.ico', '1533052800000');
INSERT INTO  `plugin` (`id`, `name`, `description`, `version`, `owner`, `status`, `current_file`, `plugin_type`, `icon`, `update_time`) VALUES ('9', 'fit2cloud-kubernetes-plugin', 'Kubernetes', '3.0', 'FIT2CLOUD', 'available', '/opt/fit2cloud/plugins/kubernetes-plugin-2.0-jar-with-dependencies.jar', 'container', 'web-public/fit2cloud/img/cloud-vendor-icon/kubernetes.ico', '1533052800000');



insert into `system_parameter` ( `param_key`, `param_value`, `type`, `sort`) values ( 'keycloak.password', 'iZV1ufy/SL0xQhsc6ePxor0PnqM4HiuIrg7rZIwYM80=', 'password', null);
insert into `system_parameter` ( `param_key`, `param_value`, `type`, `sort`) values ( 'keycloak.username', 'admin', 'text', null);

insert into `system_parameter` ( `param_key`, `param_value`, `type`, `sort`) values ( 'ui.favicon', null, 'file', '3');
insert into `system_parameter` ( `param_key`, `param_value`, `type`, `sort`) values ( 'ui.login.img', '', 'file', '7');
insert into `system_parameter` ( `param_key`, `param_value`, `type`, `sort`) values ( 'ui.login.title', '', 'text', '8');
insert into `system_parameter` ( `param_key`, `param_value`, `type`, `sort`) values ( 'ui.logo', null, 'file', '1');
insert into `system_parameter` ( `param_key`, `param_value`, `type`, `sort`) values ( 'ui.support.name', '', 'text', '9');
insert into `system_parameter` ( `param_key`, `param_value`, `type`, `sort`) values ( 'ui.support.url', '', 'text', '10');
insert into `system_parameter` ( `param_key`, `param_value`, `type`, `sort`) values ( 'ui.system.name', '', 'text', '4');
insert into `system_parameter` ( `param_key`, `param_value`, `type`, `sort`) values ( 'ui.theme.accent', ' ', 'text', '6');
insert into `system_parameter` ( `param_key`, `param_value`, `type`, `sort`) values ( 'ui.theme.primary', '', 'text', '5');
insert into `system_parameter` ( `param_key`, `param_value`, `type`, `sort`) values ( 'ui.title', '', 'text', '2');
insert into `system_parameter` ( `param_key`, `param_value`, `type`, `sort`) values ( 'ui.language', 'zh_CN', 'text', '0');


insert into `tag` ( `tag_id`, `tag_type`, `tag_key`, `tag_alias`, `enable`, `create_time`, `required`) values ( '1385228d-18d9-41e0-afb3-6f2c472ea767', 'FIT2CLOUD', 'business', '业务系统', '1', '1540200103251', '0');
insert into `tag` ( `tag_id`, `tag_type`, `tag_key`, `tag_alias`, `enable`, `create_time`, `required`) values ( 'c6056508-37d5-48f0-92bf-599b9e0e1b32', 'FIT2CLOUD', 'environment', '环境', '1', '1540200131158', '0');

insert into `tag_value` ( `id`, `tag_key`, `tag_value`, `tag_value_alias`, `create_time`) values ( '3ce8b170-d201-40b5-b0d7-b61391b5d4ed', 'environment', 'qa', '测试环境', '1540200191889');
insert into `tag_value` ( `id`, `tag_key`, `tag_value`, `tag_value_alias`, `create_time`) values ( '43b256c6-1c56-455a-90f9-b2e9cbb2da69', 'environment', 'dev', '开发环境', '1540200171919');
insert into `tag_value` ( `id`, `tag_key`, `tag_value`, `tag_value_alias`, `create_time`) values ( '7ef35167-bcf2-4820-b92c-7c271a7e63d0', 'environment', 'production', '生产环境', '1540200225655');