package com.fit2cloud.commons.server.base.domain;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

public class CloudDatastore implements Serializable {
    @ApiModelProperty("")
    private String id;

    @ApiModelProperty(value = "云账号 ID", required = true)
    private String accountId;

    @ApiModelProperty("上次同步时间")
    private Long lastSyncTimestamp;

    @ApiModelProperty("存储 ID")
    private String datastoreId;

    @ApiModelProperty("存储名称")
    private String datastoreName;

    @ApiModelProperty("容量")
    private Long capacity;

    @ApiModelProperty("剩余")
    private Long freeSpace;

    @ApiModelProperty("状态")
    private String status;

    @ApiModelProperty("存储类型")
    private String type;

    @ApiModelProperty("数据中心")
    private String region;

    @ApiModelProperty("集群")
    private String zone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cloud_datastore
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_datastore.id
     *
     * @return the value of cloud_datastore.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_datastore.id
     *
     * @param id the value for cloud_datastore.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_datastore.account_id
     *
     * @return the value of cloud_datastore.account_id
     *
     * @mbg.generated
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_datastore.account_id
     *
     * @param accountId the value for cloud_datastore.account_id
     *
     * @mbg.generated
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_datastore.last_sync_timestamp
     *
     * @return the value of cloud_datastore.last_sync_timestamp
     *
     * @mbg.generated
     */
    public Long getLastSyncTimestamp() {
        return lastSyncTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_datastore.last_sync_timestamp
     *
     * @param lastSyncTimestamp the value for cloud_datastore.last_sync_timestamp
     *
     * @mbg.generated
     */
    public void setLastSyncTimestamp(Long lastSyncTimestamp) {
        this.lastSyncTimestamp = lastSyncTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_datastore.datastore_id
     *
     * @return the value of cloud_datastore.datastore_id
     *
     * @mbg.generated
     */
    public String getDatastoreId() {
        return datastoreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_datastore.datastore_id
     *
     * @param datastoreId the value for cloud_datastore.datastore_id
     *
     * @mbg.generated
     */
    public void setDatastoreId(String datastoreId) {
        this.datastoreId = datastoreId == null ? null : datastoreId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_datastore.datastore_name
     *
     * @return the value of cloud_datastore.datastore_name
     *
     * @mbg.generated
     */
    public String getDatastoreName() {
        return datastoreName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_datastore.datastore_name
     *
     * @param datastoreName the value for cloud_datastore.datastore_name
     *
     * @mbg.generated
     */
    public void setDatastoreName(String datastoreName) {
        this.datastoreName = datastoreName == null ? null : datastoreName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_datastore.capacity
     *
     * @return the value of cloud_datastore.capacity
     *
     * @mbg.generated
     */
    public Long getCapacity() {
        return capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_datastore.capacity
     *
     * @param capacity the value for cloud_datastore.capacity
     *
     * @mbg.generated
     */
    public void setCapacity(Long capacity) {
        this.capacity = capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_datastore.free_space
     *
     * @return the value of cloud_datastore.free_space
     *
     * @mbg.generated
     */
    public Long getFreeSpace() {
        return freeSpace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_datastore.free_space
     *
     * @param freeSpace the value for cloud_datastore.free_space
     *
     * @mbg.generated
     */
    public void setFreeSpace(Long freeSpace) {
        this.freeSpace = freeSpace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_datastore.status
     *
     * @return the value of cloud_datastore.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_datastore.status
     *
     * @param status the value for cloud_datastore.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_datastore.type
     *
     * @return the value of cloud_datastore.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_datastore.type
     *
     * @param type the value for cloud_datastore.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_datastore.region
     *
     * @return the value of cloud_datastore.region
     *
     * @mbg.generated
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_datastore.region
     *
     * @param region the value for cloud_datastore.region
     *
     * @mbg.generated
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_datastore.zone
     *
     * @return the value of cloud_datastore.zone
     *
     * @mbg.generated
     */
    public String getZone() {
        return zone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_datastore.zone
     *
     * @param zone the value for cloud_datastore.zone
     *
     * @mbg.generated
     */
    public void setZone(String zone) {
        this.zone = zone == null ? null : zone.trim();
    }
}