package com.fit2cloud.commons.server.base.domain;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

public class CloudCluster implements Serializable {
    @ApiModelProperty("")
    private String id;

    @ApiModelProperty(value = "云账号 ID", required = true)
    private String accountId;

    @ApiModelProperty("数据中心")
    private String region;

    @ApiModelProperty("集群")
    private String zone;

    @ApiModelProperty("宿主机数量")
    private Integer hostCount;

    @ApiModelProperty("运行中虚拟机数")
    private Integer vmRunningCount;

    @ApiModelProperty("已停止虚拟机数")
    private Integer vmStoppedCount;

    @ApiModelProperty("CPU 总量")
    private Long cpuTotal;

    @ApiModelProperty("CPU 已分配")
    private Long cpuAllocated;

    @ApiModelProperty("内存总量")
    private Long memoryTotal;

    @ApiModelProperty("内存已分配")
    private Long memoryAllocated;

    @ApiModelProperty(value = "上次同步时间", required = true)
    private Long lastSyncTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cloud_cluster
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_cluster.id
     *
     * @return the value of cloud_cluster.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_cluster.id
     *
     * @param id the value for cloud_cluster.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_cluster.account_id
     *
     * @return the value of cloud_cluster.account_id
     *
     * @mbg.generated
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_cluster.account_id
     *
     * @param accountId the value for cloud_cluster.account_id
     *
     * @mbg.generated
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_cluster.region
     *
     * @return the value of cloud_cluster.region
     *
     * @mbg.generated
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_cluster.region
     *
     * @param region the value for cloud_cluster.region
     *
     * @mbg.generated
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_cluster.zone
     *
     * @return the value of cloud_cluster.zone
     *
     * @mbg.generated
     */
    public String getZone() {
        return zone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_cluster.zone
     *
     * @param zone the value for cloud_cluster.zone
     *
     * @mbg.generated
     */
    public void setZone(String zone) {
        this.zone = zone == null ? null : zone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_cluster.host_count
     *
     * @return the value of cloud_cluster.host_count
     *
     * @mbg.generated
     */
    public Integer getHostCount() {
        return hostCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_cluster.host_count
     *
     * @param hostCount the value for cloud_cluster.host_count
     *
     * @mbg.generated
     */
    public void setHostCount(Integer hostCount) {
        this.hostCount = hostCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_cluster.vm_running_count
     *
     * @return the value of cloud_cluster.vm_running_count
     *
     * @mbg.generated
     */
    public Integer getVmRunningCount() {
        return vmRunningCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_cluster.vm_running_count
     *
     * @param vmRunningCount the value for cloud_cluster.vm_running_count
     *
     * @mbg.generated
     */
    public void setVmRunningCount(Integer vmRunningCount) {
        this.vmRunningCount = vmRunningCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_cluster.vm_stopped_count
     *
     * @return the value of cloud_cluster.vm_stopped_count
     *
     * @mbg.generated
     */
    public Integer getVmStoppedCount() {
        return vmStoppedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_cluster.vm_stopped_count
     *
     * @param vmStoppedCount the value for cloud_cluster.vm_stopped_count
     *
     * @mbg.generated
     */
    public void setVmStoppedCount(Integer vmStoppedCount) {
        this.vmStoppedCount = vmStoppedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_cluster.cpu_total
     *
     * @return the value of cloud_cluster.cpu_total
     *
     * @mbg.generated
     */
    public Long getCpuTotal() {
        return cpuTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_cluster.cpu_total
     *
     * @param cpuTotal the value for cloud_cluster.cpu_total
     *
     * @mbg.generated
     */
    public void setCpuTotal(Long cpuTotal) {
        this.cpuTotal = cpuTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_cluster.cpu_allocated
     *
     * @return the value of cloud_cluster.cpu_allocated
     *
     * @mbg.generated
     */
    public Long getCpuAllocated() {
        return cpuAllocated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_cluster.cpu_allocated
     *
     * @param cpuAllocated the value for cloud_cluster.cpu_allocated
     *
     * @mbg.generated
     */
    public void setCpuAllocated(Long cpuAllocated) {
        this.cpuAllocated = cpuAllocated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_cluster.memory_total
     *
     * @return the value of cloud_cluster.memory_total
     *
     * @mbg.generated
     */
    public Long getMemoryTotal() {
        return memoryTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_cluster.memory_total
     *
     * @param memoryTotal the value for cloud_cluster.memory_total
     *
     * @mbg.generated
     */
    public void setMemoryTotal(Long memoryTotal) {
        this.memoryTotal = memoryTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_cluster.memory_allocated
     *
     * @return the value of cloud_cluster.memory_allocated
     *
     * @mbg.generated
     */
    public Long getMemoryAllocated() {
        return memoryAllocated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_cluster.memory_allocated
     *
     * @param memoryAllocated the value for cloud_cluster.memory_allocated
     *
     * @mbg.generated
     */
    public void setMemoryAllocated(Long memoryAllocated) {
        this.memoryAllocated = memoryAllocated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_cluster.last_sync_timestamp
     *
     * @return the value of cloud_cluster.last_sync_timestamp
     *
     * @mbg.generated
     */
    public Long getLastSyncTimestamp() {
        return lastSyncTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_cluster.last_sync_timestamp
     *
     * @param lastSyncTimestamp the value for cloud_cluster.last_sync_timestamp
     *
     * @mbg.generated
     */
    public void setLastSyncTimestamp(Long lastSyncTimestamp) {
        this.lastSyncTimestamp = lastSyncTimestamp;
    }
}