package com.fit2cloud.commons.server.base.domain;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

public class CloudHost implements Serializable {
    @ApiModelProperty("")
    private String id;

    @ApiModelProperty(value = "云账号 ID", required = true)
    private String accountId;

    @ApiModelProperty("数据中心")
    private String region;

    @ApiModelProperty("集群")
    private String zone;

    @ApiModelProperty("主机ID")
    private String hostId;

    @ApiModelProperty("主机名")
    private String hostName;

    @ApiModelProperty("CPU 总量")
    private Long cpuTotal;

    @ApiModelProperty("CPU 已分配")
    private Long cpuAllocated;

    @ApiModelProperty("内存总量")
    private Long memoryTotal;

    @ApiModelProperty("内存已分配")
    private Long memoryAllocated;

    @ApiModelProperty("虚拟机总数")
    private Long vmTotal;

    @ApiModelProperty("运行中虚拟机数")
    private Long vmRunning;

    @ApiModelProperty("已停止虚拟机数")
    private Long vmStopped;

    @ApiModelProperty("主机 IP")
    private String hostIp;

    @ApiModelProperty("主机状态")
    private String status;

    @ApiModelProperty("虚拟化类型")
    private String hypervisorType;

    @ApiModelProperty("虚拟化版本")
    private String hypervisorVersion;

    @ApiModelProperty("主机提供商")
    private String hostVendor;

    @ApiModelProperty("主机型号")
    private String hostModel;

    @ApiModelProperty("CPU 型号")
    private String cpuModel;

    @ApiModelProperty("单核 CPU 容量")
    private Integer cpuMhzPerOneCore;

    @ApiModelProperty("CPU 总数")
    private Integer numCpuCores;

    @ApiModelProperty("上次同步时间")
    private Long lastSyncTimestamp;

    @ApiModelProperty("维保日期")
    private Long maintenanceTimestamp;

    @ApiModelProperty("虚拟核数")
    private Integer vmCpuCores;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cloud_host
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_host.id
     *
     * @return the value of cloud_host.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_host.id
     *
     * @param id the value for cloud_host.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_host.account_id
     *
     * @return the value of cloud_host.account_id
     *
     * @mbg.generated
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_host.account_id
     *
     * @param accountId the value for cloud_host.account_id
     *
     * @mbg.generated
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_host.region
     *
     * @return the value of cloud_host.region
     *
     * @mbg.generated
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_host.region
     *
     * @param region the value for cloud_host.region
     *
     * @mbg.generated
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_host.zone
     *
     * @return the value of cloud_host.zone
     *
     * @mbg.generated
     */
    public String getZone() {
        return zone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_host.zone
     *
     * @param zone the value for cloud_host.zone
     *
     * @mbg.generated
     */
    public void setZone(String zone) {
        this.zone = zone == null ? null : zone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_host.host_id
     *
     * @return the value of cloud_host.host_id
     *
     * @mbg.generated
     */
    public String getHostId() {
        return hostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_host.host_id
     *
     * @param hostId the value for cloud_host.host_id
     *
     * @mbg.generated
     */
    public void setHostId(String hostId) {
        this.hostId = hostId == null ? null : hostId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_host.host_name
     *
     * @return the value of cloud_host.host_name
     *
     * @mbg.generated
     */
    public String getHostName() {
        return hostName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_host.host_name
     *
     * @param hostName the value for cloud_host.host_name
     *
     * @mbg.generated
     */
    public void setHostName(String hostName) {
        this.hostName = hostName == null ? null : hostName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_host.cpu_total
     *
     * @return the value of cloud_host.cpu_total
     *
     * @mbg.generated
     */
    public Long getCpuTotal() {
        return cpuTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_host.cpu_total
     *
     * @param cpuTotal the value for cloud_host.cpu_total
     *
     * @mbg.generated
     */
    public void setCpuTotal(Long cpuTotal) {
        this.cpuTotal = cpuTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_host.cpu_allocated
     *
     * @return the value of cloud_host.cpu_allocated
     *
     * @mbg.generated
     */
    public Long getCpuAllocated() {
        return cpuAllocated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_host.cpu_allocated
     *
     * @param cpuAllocated the value for cloud_host.cpu_allocated
     *
     * @mbg.generated
     */
    public void setCpuAllocated(Long cpuAllocated) {
        this.cpuAllocated = cpuAllocated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_host.memory_total
     *
     * @return the value of cloud_host.memory_total
     *
     * @mbg.generated
     */
    public Long getMemoryTotal() {
        return memoryTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_host.memory_total
     *
     * @param memoryTotal the value for cloud_host.memory_total
     *
     * @mbg.generated
     */
    public void setMemoryTotal(Long memoryTotal) {
        this.memoryTotal = memoryTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_host.memory_allocated
     *
     * @return the value of cloud_host.memory_allocated
     *
     * @mbg.generated
     */
    public Long getMemoryAllocated() {
        return memoryAllocated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_host.memory_allocated
     *
     * @param memoryAllocated the value for cloud_host.memory_allocated
     *
     * @mbg.generated
     */
    public void setMemoryAllocated(Long memoryAllocated) {
        this.memoryAllocated = memoryAllocated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_host.vm_total
     *
     * @return the value of cloud_host.vm_total
     *
     * @mbg.generated
     */
    public Long getVmTotal() {
        return vmTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_host.vm_total
     *
     * @param vmTotal the value for cloud_host.vm_total
     *
     * @mbg.generated
     */
    public void setVmTotal(Long vmTotal) {
        this.vmTotal = vmTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_host.vm_running
     *
     * @return the value of cloud_host.vm_running
     *
     * @mbg.generated
     */
    public Long getVmRunning() {
        return vmRunning;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_host.vm_running
     *
     * @param vmRunning the value for cloud_host.vm_running
     *
     * @mbg.generated
     */
    public void setVmRunning(Long vmRunning) {
        this.vmRunning = vmRunning;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_host.vm_stopped
     *
     * @return the value of cloud_host.vm_stopped
     *
     * @mbg.generated
     */
    public Long getVmStopped() {
        return vmStopped;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_host.vm_stopped
     *
     * @param vmStopped the value for cloud_host.vm_stopped
     *
     * @mbg.generated
     */
    public void setVmStopped(Long vmStopped) {
        this.vmStopped = vmStopped;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_host.host_ip
     *
     * @return the value of cloud_host.host_ip
     *
     * @mbg.generated
     */
    public String getHostIp() {
        return hostIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_host.host_ip
     *
     * @param hostIp the value for cloud_host.host_ip
     *
     * @mbg.generated
     */
    public void setHostIp(String hostIp) {
        this.hostIp = hostIp == null ? null : hostIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_host.status
     *
     * @return the value of cloud_host.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_host.status
     *
     * @param status the value for cloud_host.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_host.hypervisor_type
     *
     * @return the value of cloud_host.hypervisor_type
     *
     * @mbg.generated
     */
    public String getHypervisorType() {
        return hypervisorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_host.hypervisor_type
     *
     * @param hypervisorType the value for cloud_host.hypervisor_type
     *
     * @mbg.generated
     */
    public void setHypervisorType(String hypervisorType) {
        this.hypervisorType = hypervisorType == null ? null : hypervisorType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_host.hypervisor_version
     *
     * @return the value of cloud_host.hypervisor_version
     *
     * @mbg.generated
     */
    public String getHypervisorVersion() {
        return hypervisorVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_host.hypervisor_version
     *
     * @param hypervisorVersion the value for cloud_host.hypervisor_version
     *
     * @mbg.generated
     */
    public void setHypervisorVersion(String hypervisorVersion) {
        this.hypervisorVersion = hypervisorVersion == null ? null : hypervisorVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_host.host_vendor
     *
     * @return the value of cloud_host.host_vendor
     *
     * @mbg.generated
     */
    public String getHostVendor() {
        return hostVendor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_host.host_vendor
     *
     * @param hostVendor the value for cloud_host.host_vendor
     *
     * @mbg.generated
     */
    public void setHostVendor(String hostVendor) {
        this.hostVendor = hostVendor == null ? null : hostVendor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_host.host_model
     *
     * @return the value of cloud_host.host_model
     *
     * @mbg.generated
     */
    public String getHostModel() {
        return hostModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_host.host_model
     *
     * @param hostModel the value for cloud_host.host_model
     *
     * @mbg.generated
     */
    public void setHostModel(String hostModel) {
        this.hostModel = hostModel == null ? null : hostModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_host.cpu_model
     *
     * @return the value of cloud_host.cpu_model
     *
     * @mbg.generated
     */
    public String getCpuModel() {
        return cpuModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_host.cpu_model
     *
     * @param cpuModel the value for cloud_host.cpu_model
     *
     * @mbg.generated
     */
    public void setCpuModel(String cpuModel) {
        this.cpuModel = cpuModel == null ? null : cpuModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_host.cpu_mHz_per_one_core
     *
     * @return the value of cloud_host.cpu_mHz_per_one_core
     *
     * @mbg.generated
     */
    public Integer getCpuMhzPerOneCore() {
        return cpuMhzPerOneCore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_host.cpu_mHz_per_one_core
     *
     * @param cpuMhzPerOneCore the value for cloud_host.cpu_mHz_per_one_core
     *
     * @mbg.generated
     */
    public void setCpuMhzPerOneCore(Integer cpuMhzPerOneCore) {
        this.cpuMhzPerOneCore = cpuMhzPerOneCore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_host.num_cpu_cores
     *
     * @return the value of cloud_host.num_cpu_cores
     *
     * @mbg.generated
     */
    public Integer getNumCpuCores() {
        return numCpuCores;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_host.num_cpu_cores
     *
     * @param numCpuCores the value for cloud_host.num_cpu_cores
     *
     * @mbg.generated
     */
    public void setNumCpuCores(Integer numCpuCores) {
        this.numCpuCores = numCpuCores;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_host.last_sync_timestamp
     *
     * @return the value of cloud_host.last_sync_timestamp
     *
     * @mbg.generated
     */
    public Long getLastSyncTimestamp() {
        return lastSyncTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_host.last_sync_timestamp
     *
     * @param lastSyncTimestamp the value for cloud_host.last_sync_timestamp
     *
     * @mbg.generated
     */
    public void setLastSyncTimestamp(Long lastSyncTimestamp) {
        this.lastSyncTimestamp = lastSyncTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_host.maintenance_timestamp
     *
     * @return the value of cloud_host.maintenance_timestamp
     *
     * @mbg.generated
     */
    public Long getMaintenanceTimestamp() {
        return maintenanceTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_host.maintenance_timestamp
     *
     * @param maintenanceTimestamp the value for cloud_host.maintenance_timestamp
     *
     * @mbg.generated
     */
    public void setMaintenanceTimestamp(Long maintenanceTimestamp) {
        this.maintenanceTimestamp = maintenanceTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_host.vm_cpu_cores
     *
     * @return the value of cloud_host.vm_cpu_cores
     *
     * @mbg.generated
     */
    public Integer getVmCpuCores() {
        return vmCpuCores;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_host.vm_cpu_cores
     *
     * @param vmCpuCores the value for cloud_host.vm_cpu_cores
     *
     * @mbg.generated
     */
    public void setVmCpuCores(Integer vmCpuCores) {
        this.vmCpuCores = vmCpuCores;
    }
}