package com.fit2cloud.commons.server.base.domain;

import java.util.ArrayList;
import java.util.List;

public class CloudHostExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cloud_host
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cloud_host
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cloud_host
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_host
     *
     * @mbg.generated
     */
    public CloudHostExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_host
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_host
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_host
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_host
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_host
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_host
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_host
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_host
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_host
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_host
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cloud_host
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAccountIdIsNull() {
            addCriterion("account_id is null");
            return (Criteria) this;
        }

        public Criteria andAccountIdIsNotNull() {
            addCriterion("account_id is not null");
            return (Criteria) this;
        }

        public Criteria andAccountIdEqualTo(String value) {
            addCriterion("account_id =", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdNotEqualTo(String value) {
            addCriterion("account_id <>", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdGreaterThan(String value) {
            addCriterion("account_id >", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdGreaterThanOrEqualTo(String value) {
            addCriterion("account_id >=", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdLessThan(String value) {
            addCriterion("account_id <", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdLessThanOrEqualTo(String value) {
            addCriterion("account_id <=", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdLike(String value) {
            addCriterion("account_id like", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdNotLike(String value) {
            addCriterion("account_id not like", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdIn(List<String> values) {
            addCriterion("account_id in", values, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdNotIn(List<String> values) {
            addCriterion("account_id not in", values, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdBetween(String value1, String value2) {
            addCriterion("account_id between", value1, value2, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdNotBetween(String value1, String value2) {
            addCriterion("account_id not between", value1, value2, "accountId");
            return (Criteria) this;
        }

        public Criteria andRegionIsNull() {
            addCriterion("region is null");
            return (Criteria) this;
        }

        public Criteria andRegionIsNotNull() {
            addCriterion("region is not null");
            return (Criteria) this;
        }

        public Criteria andRegionEqualTo(String value) {
            addCriterion("region =", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionNotEqualTo(String value) {
            addCriterion("region <>", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionGreaterThan(String value) {
            addCriterion("region >", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionGreaterThanOrEqualTo(String value) {
            addCriterion("region >=", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionLessThan(String value) {
            addCriterion("region <", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionLessThanOrEqualTo(String value) {
            addCriterion("region <=", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionLike(String value) {
            addCriterion("region like", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionNotLike(String value) {
            addCriterion("region not like", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionIn(List<String> values) {
            addCriterion("region in", values, "region");
            return (Criteria) this;
        }

        public Criteria andRegionNotIn(List<String> values) {
            addCriterion("region not in", values, "region");
            return (Criteria) this;
        }

        public Criteria andRegionBetween(String value1, String value2) {
            addCriterion("region between", value1, value2, "region");
            return (Criteria) this;
        }

        public Criteria andRegionNotBetween(String value1, String value2) {
            addCriterion("region not between", value1, value2, "region");
            return (Criteria) this;
        }

        public Criteria andZoneIsNull() {
            addCriterion("zone is null");
            return (Criteria) this;
        }

        public Criteria andZoneIsNotNull() {
            addCriterion("zone is not null");
            return (Criteria) this;
        }

        public Criteria andZoneEqualTo(String value) {
            addCriterion("zone =", value, "zone");
            return (Criteria) this;
        }

        public Criteria andZoneNotEqualTo(String value) {
            addCriterion("zone <>", value, "zone");
            return (Criteria) this;
        }

        public Criteria andZoneGreaterThan(String value) {
            addCriterion("zone >", value, "zone");
            return (Criteria) this;
        }

        public Criteria andZoneGreaterThanOrEqualTo(String value) {
            addCriterion("zone >=", value, "zone");
            return (Criteria) this;
        }

        public Criteria andZoneLessThan(String value) {
            addCriterion("zone <", value, "zone");
            return (Criteria) this;
        }

        public Criteria andZoneLessThanOrEqualTo(String value) {
            addCriterion("zone <=", value, "zone");
            return (Criteria) this;
        }

        public Criteria andZoneLike(String value) {
            addCriterion("zone like", value, "zone");
            return (Criteria) this;
        }

        public Criteria andZoneNotLike(String value) {
            addCriterion("zone not like", value, "zone");
            return (Criteria) this;
        }

        public Criteria andZoneIn(List<String> values) {
            addCriterion("zone in", values, "zone");
            return (Criteria) this;
        }

        public Criteria andZoneNotIn(List<String> values) {
            addCriterion("zone not in", values, "zone");
            return (Criteria) this;
        }

        public Criteria andZoneBetween(String value1, String value2) {
            addCriterion("zone between", value1, value2, "zone");
            return (Criteria) this;
        }

        public Criteria andZoneNotBetween(String value1, String value2) {
            addCriterion("zone not between", value1, value2, "zone");
            return (Criteria) this;
        }

        public Criteria andHostIdIsNull() {
            addCriterion("host_id is null");
            return (Criteria) this;
        }

        public Criteria andHostIdIsNotNull() {
            addCriterion("host_id is not null");
            return (Criteria) this;
        }

        public Criteria andHostIdEqualTo(String value) {
            addCriterion("host_id =", value, "hostId");
            return (Criteria) this;
        }

        public Criteria andHostIdNotEqualTo(String value) {
            addCriterion("host_id <>", value, "hostId");
            return (Criteria) this;
        }

        public Criteria andHostIdGreaterThan(String value) {
            addCriterion("host_id >", value, "hostId");
            return (Criteria) this;
        }

        public Criteria andHostIdGreaterThanOrEqualTo(String value) {
            addCriterion("host_id >=", value, "hostId");
            return (Criteria) this;
        }

        public Criteria andHostIdLessThan(String value) {
            addCriterion("host_id <", value, "hostId");
            return (Criteria) this;
        }

        public Criteria andHostIdLessThanOrEqualTo(String value) {
            addCriterion("host_id <=", value, "hostId");
            return (Criteria) this;
        }

        public Criteria andHostIdLike(String value) {
            addCriterion("host_id like", value, "hostId");
            return (Criteria) this;
        }

        public Criteria andHostIdNotLike(String value) {
            addCriterion("host_id not like", value, "hostId");
            return (Criteria) this;
        }

        public Criteria andHostIdIn(List<String> values) {
            addCriterion("host_id in", values, "hostId");
            return (Criteria) this;
        }

        public Criteria andHostIdNotIn(List<String> values) {
            addCriterion("host_id not in", values, "hostId");
            return (Criteria) this;
        }

        public Criteria andHostIdBetween(String value1, String value2) {
            addCriterion("host_id between", value1, value2, "hostId");
            return (Criteria) this;
        }

        public Criteria andHostIdNotBetween(String value1, String value2) {
            addCriterion("host_id not between", value1, value2, "hostId");
            return (Criteria) this;
        }

        public Criteria andHostNameIsNull() {
            addCriterion("host_name is null");
            return (Criteria) this;
        }

        public Criteria andHostNameIsNotNull() {
            addCriterion("host_name is not null");
            return (Criteria) this;
        }

        public Criteria andHostNameEqualTo(String value) {
            addCriterion("host_name =", value, "hostName");
            return (Criteria) this;
        }

        public Criteria andHostNameNotEqualTo(String value) {
            addCriterion("host_name <>", value, "hostName");
            return (Criteria) this;
        }

        public Criteria andHostNameGreaterThan(String value) {
            addCriterion("host_name >", value, "hostName");
            return (Criteria) this;
        }

        public Criteria andHostNameGreaterThanOrEqualTo(String value) {
            addCriterion("host_name >=", value, "hostName");
            return (Criteria) this;
        }

        public Criteria andHostNameLessThan(String value) {
            addCriterion("host_name <", value, "hostName");
            return (Criteria) this;
        }

        public Criteria andHostNameLessThanOrEqualTo(String value) {
            addCriterion("host_name <=", value, "hostName");
            return (Criteria) this;
        }

        public Criteria andHostNameLike(String value) {
            addCriterion("host_name like", value, "hostName");
            return (Criteria) this;
        }

        public Criteria andHostNameNotLike(String value) {
            addCriterion("host_name not like", value, "hostName");
            return (Criteria) this;
        }

        public Criteria andHostNameIn(List<String> values) {
            addCriterion("host_name in", values, "hostName");
            return (Criteria) this;
        }

        public Criteria andHostNameNotIn(List<String> values) {
            addCriterion("host_name not in", values, "hostName");
            return (Criteria) this;
        }

        public Criteria andHostNameBetween(String value1, String value2) {
            addCriterion("host_name between", value1, value2, "hostName");
            return (Criteria) this;
        }

        public Criteria andHostNameNotBetween(String value1, String value2) {
            addCriterion("host_name not between", value1, value2, "hostName");
            return (Criteria) this;
        }

        public Criteria andCpuTotalIsNull() {
            addCriterion("cpu_total is null");
            return (Criteria) this;
        }

        public Criteria andCpuTotalIsNotNull() {
            addCriterion("cpu_total is not null");
            return (Criteria) this;
        }

        public Criteria andCpuTotalEqualTo(Long value) {
            addCriterion("cpu_total =", value, "cpuTotal");
            return (Criteria) this;
        }

        public Criteria andCpuTotalNotEqualTo(Long value) {
            addCriterion("cpu_total <>", value, "cpuTotal");
            return (Criteria) this;
        }

        public Criteria andCpuTotalGreaterThan(Long value) {
            addCriterion("cpu_total >", value, "cpuTotal");
            return (Criteria) this;
        }

        public Criteria andCpuTotalGreaterThanOrEqualTo(Long value) {
            addCriterion("cpu_total >=", value, "cpuTotal");
            return (Criteria) this;
        }

        public Criteria andCpuTotalLessThan(Long value) {
            addCriterion("cpu_total <", value, "cpuTotal");
            return (Criteria) this;
        }

        public Criteria andCpuTotalLessThanOrEqualTo(Long value) {
            addCriterion("cpu_total <=", value, "cpuTotal");
            return (Criteria) this;
        }

        public Criteria andCpuTotalIn(List<Long> values) {
            addCriterion("cpu_total in", values, "cpuTotal");
            return (Criteria) this;
        }

        public Criteria andCpuTotalNotIn(List<Long> values) {
            addCriterion("cpu_total not in", values, "cpuTotal");
            return (Criteria) this;
        }

        public Criteria andCpuTotalBetween(Long value1, Long value2) {
            addCriterion("cpu_total between", value1, value2, "cpuTotal");
            return (Criteria) this;
        }

        public Criteria andCpuTotalNotBetween(Long value1, Long value2) {
            addCriterion("cpu_total not between", value1, value2, "cpuTotal");
            return (Criteria) this;
        }

        public Criteria andCpuAllocatedIsNull() {
            addCriterion("cpu_allocated is null");
            return (Criteria) this;
        }

        public Criteria andCpuAllocatedIsNotNull() {
            addCriterion("cpu_allocated is not null");
            return (Criteria) this;
        }

        public Criteria andCpuAllocatedEqualTo(Long value) {
            addCriterion("cpu_allocated =", value, "cpuAllocated");
            return (Criteria) this;
        }

        public Criteria andCpuAllocatedNotEqualTo(Long value) {
            addCriterion("cpu_allocated <>", value, "cpuAllocated");
            return (Criteria) this;
        }

        public Criteria andCpuAllocatedGreaterThan(Long value) {
            addCriterion("cpu_allocated >", value, "cpuAllocated");
            return (Criteria) this;
        }

        public Criteria andCpuAllocatedGreaterThanOrEqualTo(Long value) {
            addCriterion("cpu_allocated >=", value, "cpuAllocated");
            return (Criteria) this;
        }

        public Criteria andCpuAllocatedLessThan(Long value) {
            addCriterion("cpu_allocated <", value, "cpuAllocated");
            return (Criteria) this;
        }

        public Criteria andCpuAllocatedLessThanOrEqualTo(Long value) {
            addCriterion("cpu_allocated <=", value, "cpuAllocated");
            return (Criteria) this;
        }

        public Criteria andCpuAllocatedIn(List<Long> values) {
            addCriterion("cpu_allocated in", values, "cpuAllocated");
            return (Criteria) this;
        }

        public Criteria andCpuAllocatedNotIn(List<Long> values) {
            addCriterion("cpu_allocated not in", values, "cpuAllocated");
            return (Criteria) this;
        }

        public Criteria andCpuAllocatedBetween(Long value1, Long value2) {
            addCriterion("cpu_allocated between", value1, value2, "cpuAllocated");
            return (Criteria) this;
        }

        public Criteria andCpuAllocatedNotBetween(Long value1, Long value2) {
            addCriterion("cpu_allocated not between", value1, value2, "cpuAllocated");
            return (Criteria) this;
        }

        public Criteria andMemoryTotalIsNull() {
            addCriterion("memory_total is null");
            return (Criteria) this;
        }

        public Criteria andMemoryTotalIsNotNull() {
            addCriterion("memory_total is not null");
            return (Criteria) this;
        }

        public Criteria andMemoryTotalEqualTo(Long value) {
            addCriterion("memory_total =", value, "memoryTotal");
            return (Criteria) this;
        }

        public Criteria andMemoryTotalNotEqualTo(Long value) {
            addCriterion("memory_total <>", value, "memoryTotal");
            return (Criteria) this;
        }

        public Criteria andMemoryTotalGreaterThan(Long value) {
            addCriterion("memory_total >", value, "memoryTotal");
            return (Criteria) this;
        }

        public Criteria andMemoryTotalGreaterThanOrEqualTo(Long value) {
            addCriterion("memory_total >=", value, "memoryTotal");
            return (Criteria) this;
        }

        public Criteria andMemoryTotalLessThan(Long value) {
            addCriterion("memory_total <", value, "memoryTotal");
            return (Criteria) this;
        }

        public Criteria andMemoryTotalLessThanOrEqualTo(Long value) {
            addCriterion("memory_total <=", value, "memoryTotal");
            return (Criteria) this;
        }

        public Criteria andMemoryTotalIn(List<Long> values) {
            addCriterion("memory_total in", values, "memoryTotal");
            return (Criteria) this;
        }

        public Criteria andMemoryTotalNotIn(List<Long> values) {
            addCriterion("memory_total not in", values, "memoryTotal");
            return (Criteria) this;
        }

        public Criteria andMemoryTotalBetween(Long value1, Long value2) {
            addCriterion("memory_total between", value1, value2, "memoryTotal");
            return (Criteria) this;
        }

        public Criteria andMemoryTotalNotBetween(Long value1, Long value2) {
            addCriterion("memory_total not between", value1, value2, "memoryTotal");
            return (Criteria) this;
        }

        public Criteria andMemoryAllocatedIsNull() {
            addCriterion("memory_allocated is null");
            return (Criteria) this;
        }

        public Criteria andMemoryAllocatedIsNotNull() {
            addCriterion("memory_allocated is not null");
            return (Criteria) this;
        }

        public Criteria andMemoryAllocatedEqualTo(Long value) {
            addCriterion("memory_allocated =", value, "memoryAllocated");
            return (Criteria) this;
        }

        public Criteria andMemoryAllocatedNotEqualTo(Long value) {
            addCriterion("memory_allocated <>", value, "memoryAllocated");
            return (Criteria) this;
        }

        public Criteria andMemoryAllocatedGreaterThan(Long value) {
            addCriterion("memory_allocated >", value, "memoryAllocated");
            return (Criteria) this;
        }

        public Criteria andMemoryAllocatedGreaterThanOrEqualTo(Long value) {
            addCriterion("memory_allocated >=", value, "memoryAllocated");
            return (Criteria) this;
        }

        public Criteria andMemoryAllocatedLessThan(Long value) {
            addCriterion("memory_allocated <", value, "memoryAllocated");
            return (Criteria) this;
        }

        public Criteria andMemoryAllocatedLessThanOrEqualTo(Long value) {
            addCriterion("memory_allocated <=", value, "memoryAllocated");
            return (Criteria) this;
        }

        public Criteria andMemoryAllocatedIn(List<Long> values) {
            addCriterion("memory_allocated in", values, "memoryAllocated");
            return (Criteria) this;
        }

        public Criteria andMemoryAllocatedNotIn(List<Long> values) {
            addCriterion("memory_allocated not in", values, "memoryAllocated");
            return (Criteria) this;
        }

        public Criteria andMemoryAllocatedBetween(Long value1, Long value2) {
            addCriterion("memory_allocated between", value1, value2, "memoryAllocated");
            return (Criteria) this;
        }

        public Criteria andMemoryAllocatedNotBetween(Long value1, Long value2) {
            addCriterion("memory_allocated not between", value1, value2, "memoryAllocated");
            return (Criteria) this;
        }

        public Criteria andVmTotalIsNull() {
            addCriterion("vm_total is null");
            return (Criteria) this;
        }

        public Criteria andVmTotalIsNotNull() {
            addCriterion("vm_total is not null");
            return (Criteria) this;
        }

        public Criteria andVmTotalEqualTo(Long value) {
            addCriterion("vm_total =", value, "vmTotal");
            return (Criteria) this;
        }

        public Criteria andVmTotalNotEqualTo(Long value) {
            addCriterion("vm_total <>", value, "vmTotal");
            return (Criteria) this;
        }

        public Criteria andVmTotalGreaterThan(Long value) {
            addCriterion("vm_total >", value, "vmTotal");
            return (Criteria) this;
        }

        public Criteria andVmTotalGreaterThanOrEqualTo(Long value) {
            addCriterion("vm_total >=", value, "vmTotal");
            return (Criteria) this;
        }

        public Criteria andVmTotalLessThan(Long value) {
            addCriterion("vm_total <", value, "vmTotal");
            return (Criteria) this;
        }

        public Criteria andVmTotalLessThanOrEqualTo(Long value) {
            addCriterion("vm_total <=", value, "vmTotal");
            return (Criteria) this;
        }

        public Criteria andVmTotalIn(List<Long> values) {
            addCriterion("vm_total in", values, "vmTotal");
            return (Criteria) this;
        }

        public Criteria andVmTotalNotIn(List<Long> values) {
            addCriterion("vm_total not in", values, "vmTotal");
            return (Criteria) this;
        }

        public Criteria andVmTotalBetween(Long value1, Long value2) {
            addCriterion("vm_total between", value1, value2, "vmTotal");
            return (Criteria) this;
        }

        public Criteria andVmTotalNotBetween(Long value1, Long value2) {
            addCriterion("vm_total not between", value1, value2, "vmTotal");
            return (Criteria) this;
        }

        public Criteria andVmRunningIsNull() {
            addCriterion("vm_running is null");
            return (Criteria) this;
        }

        public Criteria andVmRunningIsNotNull() {
            addCriterion("vm_running is not null");
            return (Criteria) this;
        }

        public Criteria andVmRunningEqualTo(Long value) {
            addCriterion("vm_running =", value, "vmRunning");
            return (Criteria) this;
        }

        public Criteria andVmRunningNotEqualTo(Long value) {
            addCriterion("vm_running <>", value, "vmRunning");
            return (Criteria) this;
        }

        public Criteria andVmRunningGreaterThan(Long value) {
            addCriterion("vm_running >", value, "vmRunning");
            return (Criteria) this;
        }

        public Criteria andVmRunningGreaterThanOrEqualTo(Long value) {
            addCriterion("vm_running >=", value, "vmRunning");
            return (Criteria) this;
        }

        public Criteria andVmRunningLessThan(Long value) {
            addCriterion("vm_running <", value, "vmRunning");
            return (Criteria) this;
        }

        public Criteria andVmRunningLessThanOrEqualTo(Long value) {
            addCriterion("vm_running <=", value, "vmRunning");
            return (Criteria) this;
        }

        public Criteria andVmRunningIn(List<Long> values) {
            addCriterion("vm_running in", values, "vmRunning");
            return (Criteria) this;
        }

        public Criteria andVmRunningNotIn(List<Long> values) {
            addCriterion("vm_running not in", values, "vmRunning");
            return (Criteria) this;
        }

        public Criteria andVmRunningBetween(Long value1, Long value2) {
            addCriterion("vm_running between", value1, value2, "vmRunning");
            return (Criteria) this;
        }

        public Criteria andVmRunningNotBetween(Long value1, Long value2) {
            addCriterion("vm_running not between", value1, value2, "vmRunning");
            return (Criteria) this;
        }

        public Criteria andVmStoppedIsNull() {
            addCriterion("vm_stopped is null");
            return (Criteria) this;
        }

        public Criteria andVmStoppedIsNotNull() {
            addCriterion("vm_stopped is not null");
            return (Criteria) this;
        }

        public Criteria andVmStoppedEqualTo(Long value) {
            addCriterion("vm_stopped =", value, "vmStopped");
            return (Criteria) this;
        }

        public Criteria andVmStoppedNotEqualTo(Long value) {
            addCriterion("vm_stopped <>", value, "vmStopped");
            return (Criteria) this;
        }

        public Criteria andVmStoppedGreaterThan(Long value) {
            addCriterion("vm_stopped >", value, "vmStopped");
            return (Criteria) this;
        }

        public Criteria andVmStoppedGreaterThanOrEqualTo(Long value) {
            addCriterion("vm_stopped >=", value, "vmStopped");
            return (Criteria) this;
        }

        public Criteria andVmStoppedLessThan(Long value) {
            addCriterion("vm_stopped <", value, "vmStopped");
            return (Criteria) this;
        }

        public Criteria andVmStoppedLessThanOrEqualTo(Long value) {
            addCriterion("vm_stopped <=", value, "vmStopped");
            return (Criteria) this;
        }

        public Criteria andVmStoppedIn(List<Long> values) {
            addCriterion("vm_stopped in", values, "vmStopped");
            return (Criteria) this;
        }

        public Criteria andVmStoppedNotIn(List<Long> values) {
            addCriterion("vm_stopped not in", values, "vmStopped");
            return (Criteria) this;
        }

        public Criteria andVmStoppedBetween(Long value1, Long value2) {
            addCriterion("vm_stopped between", value1, value2, "vmStopped");
            return (Criteria) this;
        }

        public Criteria andVmStoppedNotBetween(Long value1, Long value2) {
            addCriterion("vm_stopped not between", value1, value2, "vmStopped");
            return (Criteria) this;
        }

        public Criteria andHostIpIsNull() {
            addCriterion("host_ip is null");
            return (Criteria) this;
        }

        public Criteria andHostIpIsNotNull() {
            addCriterion("host_ip is not null");
            return (Criteria) this;
        }

        public Criteria andHostIpEqualTo(String value) {
            addCriterion("host_ip =", value, "hostIp");
            return (Criteria) this;
        }

        public Criteria andHostIpNotEqualTo(String value) {
            addCriterion("host_ip <>", value, "hostIp");
            return (Criteria) this;
        }

        public Criteria andHostIpGreaterThan(String value) {
            addCriterion("host_ip >", value, "hostIp");
            return (Criteria) this;
        }

        public Criteria andHostIpGreaterThanOrEqualTo(String value) {
            addCriterion("host_ip >=", value, "hostIp");
            return (Criteria) this;
        }

        public Criteria andHostIpLessThan(String value) {
            addCriterion("host_ip <", value, "hostIp");
            return (Criteria) this;
        }

        public Criteria andHostIpLessThanOrEqualTo(String value) {
            addCriterion("host_ip <=", value, "hostIp");
            return (Criteria) this;
        }

        public Criteria andHostIpLike(String value) {
            addCriterion("host_ip like", value, "hostIp");
            return (Criteria) this;
        }

        public Criteria andHostIpNotLike(String value) {
            addCriterion("host_ip not like", value, "hostIp");
            return (Criteria) this;
        }

        public Criteria andHostIpIn(List<String> values) {
            addCriterion("host_ip in", values, "hostIp");
            return (Criteria) this;
        }

        public Criteria andHostIpNotIn(List<String> values) {
            addCriterion("host_ip not in", values, "hostIp");
            return (Criteria) this;
        }

        public Criteria andHostIpBetween(String value1, String value2) {
            addCriterion("host_ip between", value1, value2, "hostIp");
            return (Criteria) this;
        }

        public Criteria andHostIpNotBetween(String value1, String value2) {
            addCriterion("host_ip not between", value1, value2, "hostIp");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andHypervisorTypeIsNull() {
            addCriterion("hypervisor_type is null");
            return (Criteria) this;
        }

        public Criteria andHypervisorTypeIsNotNull() {
            addCriterion("hypervisor_type is not null");
            return (Criteria) this;
        }

        public Criteria andHypervisorTypeEqualTo(String value) {
            addCriterion("hypervisor_type =", value, "hypervisorType");
            return (Criteria) this;
        }

        public Criteria andHypervisorTypeNotEqualTo(String value) {
            addCriterion("hypervisor_type <>", value, "hypervisorType");
            return (Criteria) this;
        }

        public Criteria andHypervisorTypeGreaterThan(String value) {
            addCriterion("hypervisor_type >", value, "hypervisorType");
            return (Criteria) this;
        }

        public Criteria andHypervisorTypeGreaterThanOrEqualTo(String value) {
            addCriterion("hypervisor_type >=", value, "hypervisorType");
            return (Criteria) this;
        }

        public Criteria andHypervisorTypeLessThan(String value) {
            addCriterion("hypervisor_type <", value, "hypervisorType");
            return (Criteria) this;
        }

        public Criteria andHypervisorTypeLessThanOrEqualTo(String value) {
            addCriterion("hypervisor_type <=", value, "hypervisorType");
            return (Criteria) this;
        }

        public Criteria andHypervisorTypeLike(String value) {
            addCriterion("hypervisor_type like", value, "hypervisorType");
            return (Criteria) this;
        }

        public Criteria andHypervisorTypeNotLike(String value) {
            addCriterion("hypervisor_type not like", value, "hypervisorType");
            return (Criteria) this;
        }

        public Criteria andHypervisorTypeIn(List<String> values) {
            addCriterion("hypervisor_type in", values, "hypervisorType");
            return (Criteria) this;
        }

        public Criteria andHypervisorTypeNotIn(List<String> values) {
            addCriterion("hypervisor_type not in", values, "hypervisorType");
            return (Criteria) this;
        }

        public Criteria andHypervisorTypeBetween(String value1, String value2) {
            addCriterion("hypervisor_type between", value1, value2, "hypervisorType");
            return (Criteria) this;
        }

        public Criteria andHypervisorTypeNotBetween(String value1, String value2) {
            addCriterion("hypervisor_type not between", value1, value2, "hypervisorType");
            return (Criteria) this;
        }

        public Criteria andHypervisorVersionIsNull() {
            addCriterion("hypervisor_version is null");
            return (Criteria) this;
        }

        public Criteria andHypervisorVersionIsNotNull() {
            addCriterion("hypervisor_version is not null");
            return (Criteria) this;
        }

        public Criteria andHypervisorVersionEqualTo(String value) {
            addCriterion("hypervisor_version =", value, "hypervisorVersion");
            return (Criteria) this;
        }

        public Criteria andHypervisorVersionNotEqualTo(String value) {
            addCriterion("hypervisor_version <>", value, "hypervisorVersion");
            return (Criteria) this;
        }

        public Criteria andHypervisorVersionGreaterThan(String value) {
            addCriterion("hypervisor_version >", value, "hypervisorVersion");
            return (Criteria) this;
        }

        public Criteria andHypervisorVersionGreaterThanOrEqualTo(String value) {
            addCriterion("hypervisor_version >=", value, "hypervisorVersion");
            return (Criteria) this;
        }

        public Criteria andHypervisorVersionLessThan(String value) {
            addCriterion("hypervisor_version <", value, "hypervisorVersion");
            return (Criteria) this;
        }

        public Criteria andHypervisorVersionLessThanOrEqualTo(String value) {
            addCriterion("hypervisor_version <=", value, "hypervisorVersion");
            return (Criteria) this;
        }

        public Criteria andHypervisorVersionLike(String value) {
            addCriterion("hypervisor_version like", value, "hypervisorVersion");
            return (Criteria) this;
        }

        public Criteria andHypervisorVersionNotLike(String value) {
            addCriterion("hypervisor_version not like", value, "hypervisorVersion");
            return (Criteria) this;
        }

        public Criteria andHypervisorVersionIn(List<String> values) {
            addCriterion("hypervisor_version in", values, "hypervisorVersion");
            return (Criteria) this;
        }

        public Criteria andHypervisorVersionNotIn(List<String> values) {
            addCriterion("hypervisor_version not in", values, "hypervisorVersion");
            return (Criteria) this;
        }

        public Criteria andHypervisorVersionBetween(String value1, String value2) {
            addCriterion("hypervisor_version between", value1, value2, "hypervisorVersion");
            return (Criteria) this;
        }

        public Criteria andHypervisorVersionNotBetween(String value1, String value2) {
            addCriterion("hypervisor_version not between", value1, value2, "hypervisorVersion");
            return (Criteria) this;
        }

        public Criteria andHostVendorIsNull() {
            addCriterion("host_vendor is null");
            return (Criteria) this;
        }

        public Criteria andHostVendorIsNotNull() {
            addCriterion("host_vendor is not null");
            return (Criteria) this;
        }

        public Criteria andHostVendorEqualTo(String value) {
            addCriterion("host_vendor =", value, "hostVendor");
            return (Criteria) this;
        }

        public Criteria andHostVendorNotEqualTo(String value) {
            addCriterion("host_vendor <>", value, "hostVendor");
            return (Criteria) this;
        }

        public Criteria andHostVendorGreaterThan(String value) {
            addCriterion("host_vendor >", value, "hostVendor");
            return (Criteria) this;
        }

        public Criteria andHostVendorGreaterThanOrEqualTo(String value) {
            addCriterion("host_vendor >=", value, "hostVendor");
            return (Criteria) this;
        }

        public Criteria andHostVendorLessThan(String value) {
            addCriterion("host_vendor <", value, "hostVendor");
            return (Criteria) this;
        }

        public Criteria andHostVendorLessThanOrEqualTo(String value) {
            addCriterion("host_vendor <=", value, "hostVendor");
            return (Criteria) this;
        }

        public Criteria andHostVendorLike(String value) {
            addCriterion("host_vendor like", value, "hostVendor");
            return (Criteria) this;
        }

        public Criteria andHostVendorNotLike(String value) {
            addCriterion("host_vendor not like", value, "hostVendor");
            return (Criteria) this;
        }

        public Criteria andHostVendorIn(List<String> values) {
            addCriterion("host_vendor in", values, "hostVendor");
            return (Criteria) this;
        }

        public Criteria andHostVendorNotIn(List<String> values) {
            addCriterion("host_vendor not in", values, "hostVendor");
            return (Criteria) this;
        }

        public Criteria andHostVendorBetween(String value1, String value2) {
            addCriterion("host_vendor between", value1, value2, "hostVendor");
            return (Criteria) this;
        }

        public Criteria andHostVendorNotBetween(String value1, String value2) {
            addCriterion("host_vendor not between", value1, value2, "hostVendor");
            return (Criteria) this;
        }

        public Criteria andHostModelIsNull() {
            addCriterion("host_model is null");
            return (Criteria) this;
        }

        public Criteria andHostModelIsNotNull() {
            addCriterion("host_model is not null");
            return (Criteria) this;
        }

        public Criteria andHostModelEqualTo(String value) {
            addCriterion("host_model =", value, "hostModel");
            return (Criteria) this;
        }

        public Criteria andHostModelNotEqualTo(String value) {
            addCriterion("host_model <>", value, "hostModel");
            return (Criteria) this;
        }

        public Criteria andHostModelGreaterThan(String value) {
            addCriterion("host_model >", value, "hostModel");
            return (Criteria) this;
        }

        public Criteria andHostModelGreaterThanOrEqualTo(String value) {
            addCriterion("host_model >=", value, "hostModel");
            return (Criteria) this;
        }

        public Criteria andHostModelLessThan(String value) {
            addCriterion("host_model <", value, "hostModel");
            return (Criteria) this;
        }

        public Criteria andHostModelLessThanOrEqualTo(String value) {
            addCriterion("host_model <=", value, "hostModel");
            return (Criteria) this;
        }

        public Criteria andHostModelLike(String value) {
            addCriterion("host_model like", value, "hostModel");
            return (Criteria) this;
        }

        public Criteria andHostModelNotLike(String value) {
            addCriterion("host_model not like", value, "hostModel");
            return (Criteria) this;
        }

        public Criteria andHostModelIn(List<String> values) {
            addCriterion("host_model in", values, "hostModel");
            return (Criteria) this;
        }

        public Criteria andHostModelNotIn(List<String> values) {
            addCriterion("host_model not in", values, "hostModel");
            return (Criteria) this;
        }

        public Criteria andHostModelBetween(String value1, String value2) {
            addCriterion("host_model between", value1, value2, "hostModel");
            return (Criteria) this;
        }

        public Criteria andHostModelNotBetween(String value1, String value2) {
            addCriterion("host_model not between", value1, value2, "hostModel");
            return (Criteria) this;
        }

        public Criteria andCpuModelIsNull() {
            addCriterion("cpu_model is null");
            return (Criteria) this;
        }

        public Criteria andCpuModelIsNotNull() {
            addCriterion("cpu_model is not null");
            return (Criteria) this;
        }

        public Criteria andCpuModelEqualTo(String value) {
            addCriterion("cpu_model =", value, "cpuModel");
            return (Criteria) this;
        }

        public Criteria andCpuModelNotEqualTo(String value) {
            addCriterion("cpu_model <>", value, "cpuModel");
            return (Criteria) this;
        }

        public Criteria andCpuModelGreaterThan(String value) {
            addCriterion("cpu_model >", value, "cpuModel");
            return (Criteria) this;
        }

        public Criteria andCpuModelGreaterThanOrEqualTo(String value) {
            addCriterion("cpu_model >=", value, "cpuModel");
            return (Criteria) this;
        }

        public Criteria andCpuModelLessThan(String value) {
            addCriterion("cpu_model <", value, "cpuModel");
            return (Criteria) this;
        }

        public Criteria andCpuModelLessThanOrEqualTo(String value) {
            addCriterion("cpu_model <=", value, "cpuModel");
            return (Criteria) this;
        }

        public Criteria andCpuModelLike(String value) {
            addCriterion("cpu_model like", value, "cpuModel");
            return (Criteria) this;
        }

        public Criteria andCpuModelNotLike(String value) {
            addCriterion("cpu_model not like", value, "cpuModel");
            return (Criteria) this;
        }

        public Criteria andCpuModelIn(List<String> values) {
            addCriterion("cpu_model in", values, "cpuModel");
            return (Criteria) this;
        }

        public Criteria andCpuModelNotIn(List<String> values) {
            addCriterion("cpu_model not in", values, "cpuModel");
            return (Criteria) this;
        }

        public Criteria andCpuModelBetween(String value1, String value2) {
            addCriterion("cpu_model between", value1, value2, "cpuModel");
            return (Criteria) this;
        }

        public Criteria andCpuModelNotBetween(String value1, String value2) {
            addCriterion("cpu_model not between", value1, value2, "cpuModel");
            return (Criteria) this;
        }

        public Criteria andCpuMhzPerOneCoreIsNull() {
            addCriterion("cpu_mHz_per_one_core is null");
            return (Criteria) this;
        }

        public Criteria andCpuMhzPerOneCoreIsNotNull() {
            addCriterion("cpu_mHz_per_one_core is not null");
            return (Criteria) this;
        }

        public Criteria andCpuMhzPerOneCoreEqualTo(Integer value) {
            addCriterion("cpu_mHz_per_one_core =", value, "cpuMhzPerOneCore");
            return (Criteria) this;
        }

        public Criteria andCpuMhzPerOneCoreNotEqualTo(Integer value) {
            addCriterion("cpu_mHz_per_one_core <>", value, "cpuMhzPerOneCore");
            return (Criteria) this;
        }

        public Criteria andCpuMhzPerOneCoreGreaterThan(Integer value) {
            addCriterion("cpu_mHz_per_one_core >", value, "cpuMhzPerOneCore");
            return (Criteria) this;
        }

        public Criteria andCpuMhzPerOneCoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("cpu_mHz_per_one_core >=", value, "cpuMhzPerOneCore");
            return (Criteria) this;
        }

        public Criteria andCpuMhzPerOneCoreLessThan(Integer value) {
            addCriterion("cpu_mHz_per_one_core <", value, "cpuMhzPerOneCore");
            return (Criteria) this;
        }

        public Criteria andCpuMhzPerOneCoreLessThanOrEqualTo(Integer value) {
            addCriterion("cpu_mHz_per_one_core <=", value, "cpuMhzPerOneCore");
            return (Criteria) this;
        }

        public Criteria andCpuMhzPerOneCoreIn(List<Integer> values) {
            addCriterion("cpu_mHz_per_one_core in", values, "cpuMhzPerOneCore");
            return (Criteria) this;
        }

        public Criteria andCpuMhzPerOneCoreNotIn(List<Integer> values) {
            addCriterion("cpu_mHz_per_one_core not in", values, "cpuMhzPerOneCore");
            return (Criteria) this;
        }

        public Criteria andCpuMhzPerOneCoreBetween(Integer value1, Integer value2) {
            addCriterion("cpu_mHz_per_one_core between", value1, value2, "cpuMhzPerOneCore");
            return (Criteria) this;
        }

        public Criteria andCpuMhzPerOneCoreNotBetween(Integer value1, Integer value2) {
            addCriterion("cpu_mHz_per_one_core not between", value1, value2, "cpuMhzPerOneCore");
            return (Criteria) this;
        }

        public Criteria andNumCpuCoresIsNull() {
            addCriterion("num_cpu_cores is null");
            return (Criteria) this;
        }

        public Criteria andNumCpuCoresIsNotNull() {
            addCriterion("num_cpu_cores is not null");
            return (Criteria) this;
        }

        public Criteria andNumCpuCoresEqualTo(Integer value) {
            addCriterion("num_cpu_cores =", value, "numCpuCores");
            return (Criteria) this;
        }

        public Criteria andNumCpuCoresNotEqualTo(Integer value) {
            addCriterion("num_cpu_cores <>", value, "numCpuCores");
            return (Criteria) this;
        }

        public Criteria andNumCpuCoresGreaterThan(Integer value) {
            addCriterion("num_cpu_cores >", value, "numCpuCores");
            return (Criteria) this;
        }

        public Criteria andNumCpuCoresGreaterThanOrEqualTo(Integer value) {
            addCriterion("num_cpu_cores >=", value, "numCpuCores");
            return (Criteria) this;
        }

        public Criteria andNumCpuCoresLessThan(Integer value) {
            addCriterion("num_cpu_cores <", value, "numCpuCores");
            return (Criteria) this;
        }

        public Criteria andNumCpuCoresLessThanOrEqualTo(Integer value) {
            addCriterion("num_cpu_cores <=", value, "numCpuCores");
            return (Criteria) this;
        }

        public Criteria andNumCpuCoresIn(List<Integer> values) {
            addCriterion("num_cpu_cores in", values, "numCpuCores");
            return (Criteria) this;
        }

        public Criteria andNumCpuCoresNotIn(List<Integer> values) {
            addCriterion("num_cpu_cores not in", values, "numCpuCores");
            return (Criteria) this;
        }

        public Criteria andNumCpuCoresBetween(Integer value1, Integer value2) {
            addCriterion("num_cpu_cores between", value1, value2, "numCpuCores");
            return (Criteria) this;
        }

        public Criteria andNumCpuCoresNotBetween(Integer value1, Integer value2) {
            addCriterion("num_cpu_cores not between", value1, value2, "numCpuCores");
            return (Criteria) this;
        }

        public Criteria andLastSyncTimestampIsNull() {
            addCriterion("last_sync_timestamp is null");
            return (Criteria) this;
        }

        public Criteria andLastSyncTimestampIsNotNull() {
            addCriterion("last_sync_timestamp is not null");
            return (Criteria) this;
        }

        public Criteria andLastSyncTimestampEqualTo(Long value) {
            addCriterion("last_sync_timestamp =", value, "lastSyncTimestamp");
            return (Criteria) this;
        }

        public Criteria andLastSyncTimestampNotEqualTo(Long value) {
            addCriterion("last_sync_timestamp <>", value, "lastSyncTimestamp");
            return (Criteria) this;
        }

        public Criteria andLastSyncTimestampGreaterThan(Long value) {
            addCriterion("last_sync_timestamp >", value, "lastSyncTimestamp");
            return (Criteria) this;
        }

        public Criteria andLastSyncTimestampGreaterThanOrEqualTo(Long value) {
            addCriterion("last_sync_timestamp >=", value, "lastSyncTimestamp");
            return (Criteria) this;
        }

        public Criteria andLastSyncTimestampLessThan(Long value) {
            addCriterion("last_sync_timestamp <", value, "lastSyncTimestamp");
            return (Criteria) this;
        }

        public Criteria andLastSyncTimestampLessThanOrEqualTo(Long value) {
            addCriterion("last_sync_timestamp <=", value, "lastSyncTimestamp");
            return (Criteria) this;
        }

        public Criteria andLastSyncTimestampIn(List<Long> values) {
            addCriterion("last_sync_timestamp in", values, "lastSyncTimestamp");
            return (Criteria) this;
        }

        public Criteria andLastSyncTimestampNotIn(List<Long> values) {
            addCriterion("last_sync_timestamp not in", values, "lastSyncTimestamp");
            return (Criteria) this;
        }

        public Criteria andLastSyncTimestampBetween(Long value1, Long value2) {
            addCriterion("last_sync_timestamp between", value1, value2, "lastSyncTimestamp");
            return (Criteria) this;
        }

        public Criteria andLastSyncTimestampNotBetween(Long value1, Long value2) {
            addCriterion("last_sync_timestamp not between", value1, value2, "lastSyncTimestamp");
            return (Criteria) this;
        }

        public Criteria andMaintenanceTimestampIsNull() {
            addCriterion("maintenance_timestamp is null");
            return (Criteria) this;
        }

        public Criteria andMaintenanceTimestampIsNotNull() {
            addCriterion("maintenance_timestamp is not null");
            return (Criteria) this;
        }

        public Criteria andMaintenanceTimestampEqualTo(Long value) {
            addCriterion("maintenance_timestamp =", value, "maintenanceTimestamp");
            return (Criteria) this;
        }

        public Criteria andMaintenanceTimestampNotEqualTo(Long value) {
            addCriterion("maintenance_timestamp <>", value, "maintenanceTimestamp");
            return (Criteria) this;
        }

        public Criteria andMaintenanceTimestampGreaterThan(Long value) {
            addCriterion("maintenance_timestamp >", value, "maintenanceTimestamp");
            return (Criteria) this;
        }

        public Criteria andMaintenanceTimestampGreaterThanOrEqualTo(Long value) {
            addCriterion("maintenance_timestamp >=", value, "maintenanceTimestamp");
            return (Criteria) this;
        }

        public Criteria andMaintenanceTimestampLessThan(Long value) {
            addCriterion("maintenance_timestamp <", value, "maintenanceTimestamp");
            return (Criteria) this;
        }

        public Criteria andMaintenanceTimestampLessThanOrEqualTo(Long value) {
            addCriterion("maintenance_timestamp <=", value, "maintenanceTimestamp");
            return (Criteria) this;
        }

        public Criteria andMaintenanceTimestampIn(List<Long> values) {
            addCriterion("maintenance_timestamp in", values, "maintenanceTimestamp");
            return (Criteria) this;
        }

        public Criteria andMaintenanceTimestampNotIn(List<Long> values) {
            addCriterion("maintenance_timestamp not in", values, "maintenanceTimestamp");
            return (Criteria) this;
        }

        public Criteria andMaintenanceTimestampBetween(Long value1, Long value2) {
            addCriterion("maintenance_timestamp between", value1, value2, "maintenanceTimestamp");
            return (Criteria) this;
        }

        public Criteria andMaintenanceTimestampNotBetween(Long value1, Long value2) {
            addCriterion("maintenance_timestamp not between", value1, value2, "maintenanceTimestamp");
            return (Criteria) this;
        }

        public Criteria andVmCpuCoresIsNull() {
            addCriterion("vm_cpu_cores is null");
            return (Criteria) this;
        }

        public Criteria andVmCpuCoresIsNotNull() {
            addCriterion("vm_cpu_cores is not null");
            return (Criteria) this;
        }

        public Criteria andVmCpuCoresEqualTo(Integer value) {
            addCriterion("vm_cpu_cores =", value, "vmCpuCores");
            return (Criteria) this;
        }

        public Criteria andVmCpuCoresNotEqualTo(Integer value) {
            addCriterion("vm_cpu_cores <>", value, "vmCpuCores");
            return (Criteria) this;
        }

        public Criteria andVmCpuCoresGreaterThan(Integer value) {
            addCriterion("vm_cpu_cores >", value, "vmCpuCores");
            return (Criteria) this;
        }

        public Criteria andVmCpuCoresGreaterThanOrEqualTo(Integer value) {
            addCriterion("vm_cpu_cores >=", value, "vmCpuCores");
            return (Criteria) this;
        }

        public Criteria andVmCpuCoresLessThan(Integer value) {
            addCriterion("vm_cpu_cores <", value, "vmCpuCores");
            return (Criteria) this;
        }

        public Criteria andVmCpuCoresLessThanOrEqualTo(Integer value) {
            addCriterion("vm_cpu_cores <=", value, "vmCpuCores");
            return (Criteria) this;
        }

        public Criteria andVmCpuCoresIn(List<Integer> values) {
            addCriterion("vm_cpu_cores in", values, "vmCpuCores");
            return (Criteria) this;
        }

        public Criteria andVmCpuCoresNotIn(List<Integer> values) {
            addCriterion("vm_cpu_cores not in", values, "vmCpuCores");
            return (Criteria) this;
        }

        public Criteria andVmCpuCoresBetween(Integer value1, Integer value2) {
            addCriterion("vm_cpu_cores between", value1, value2, "vmCpuCores");
            return (Criteria) this;
        }

        public Criteria andVmCpuCoresNotBetween(Integer value1, Integer value2) {
            addCriterion("vm_cpu_cores not between", value1, value2, "vmCpuCores");
            return (Criteria) this;
        }

        public Criteria andSqlCriterion(String value) {
            addCriterion("(" + value + ")");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cloud_host
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cloud_host
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}