package com.fit2cloud.commons.server.base.domain;

import java.util.ArrayList;
import java.util.List;

public class CloudClusterExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cloud_cluster
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cloud_cluster
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cloud_cluster
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_cluster
     *
     * @mbg.generated
     */
    public CloudClusterExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_cluster
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_cluster
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_cluster
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_cluster
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_cluster
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_cluster
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_cluster
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_cluster
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_cluster
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_cluster
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cloud_cluster
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAccountIdIsNull() {
            addCriterion("account_id is null");
            return (Criteria) this;
        }

        public Criteria andAccountIdIsNotNull() {
            addCriterion("account_id is not null");
            return (Criteria) this;
        }

        public Criteria andAccountIdEqualTo(String value) {
            addCriterion("account_id =", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdNotEqualTo(String value) {
            addCriterion("account_id <>", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdGreaterThan(String value) {
            addCriterion("account_id >", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdGreaterThanOrEqualTo(String value) {
            addCriterion("account_id >=", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdLessThan(String value) {
            addCriterion("account_id <", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdLessThanOrEqualTo(String value) {
            addCriterion("account_id <=", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdLike(String value) {
            addCriterion("account_id like", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdNotLike(String value) {
            addCriterion("account_id not like", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdIn(List<String> values) {
            addCriterion("account_id in", values, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdNotIn(List<String> values) {
            addCriterion("account_id not in", values, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdBetween(String value1, String value2) {
            addCriterion("account_id between", value1, value2, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdNotBetween(String value1, String value2) {
            addCriterion("account_id not between", value1, value2, "accountId");
            return (Criteria) this;
        }

        public Criteria andRegionIsNull() {
            addCriterion("region is null");
            return (Criteria) this;
        }

        public Criteria andRegionIsNotNull() {
            addCriterion("region is not null");
            return (Criteria) this;
        }

        public Criteria andRegionEqualTo(String value) {
            addCriterion("region =", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionNotEqualTo(String value) {
            addCriterion("region <>", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionGreaterThan(String value) {
            addCriterion("region >", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionGreaterThanOrEqualTo(String value) {
            addCriterion("region >=", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionLessThan(String value) {
            addCriterion("region <", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionLessThanOrEqualTo(String value) {
            addCriterion("region <=", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionLike(String value) {
            addCriterion("region like", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionNotLike(String value) {
            addCriterion("region not like", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionIn(List<String> values) {
            addCriterion("region in", values, "region");
            return (Criteria) this;
        }

        public Criteria andRegionNotIn(List<String> values) {
            addCriterion("region not in", values, "region");
            return (Criteria) this;
        }

        public Criteria andRegionBetween(String value1, String value2) {
            addCriterion("region between", value1, value2, "region");
            return (Criteria) this;
        }

        public Criteria andRegionNotBetween(String value1, String value2) {
            addCriterion("region not between", value1, value2, "region");
            return (Criteria) this;
        }

        public Criteria andZoneIsNull() {
            addCriterion("zone is null");
            return (Criteria) this;
        }

        public Criteria andZoneIsNotNull() {
            addCriterion("zone is not null");
            return (Criteria) this;
        }

        public Criteria andZoneEqualTo(String value) {
            addCriterion("zone =", value, "zone");
            return (Criteria) this;
        }

        public Criteria andZoneNotEqualTo(String value) {
            addCriterion("zone <>", value, "zone");
            return (Criteria) this;
        }

        public Criteria andZoneGreaterThan(String value) {
            addCriterion("zone >", value, "zone");
            return (Criteria) this;
        }

        public Criteria andZoneGreaterThanOrEqualTo(String value) {
            addCriterion("zone >=", value, "zone");
            return (Criteria) this;
        }

        public Criteria andZoneLessThan(String value) {
            addCriterion("zone <", value, "zone");
            return (Criteria) this;
        }

        public Criteria andZoneLessThanOrEqualTo(String value) {
            addCriterion("zone <=", value, "zone");
            return (Criteria) this;
        }

        public Criteria andZoneLike(String value) {
            addCriterion("zone like", value, "zone");
            return (Criteria) this;
        }

        public Criteria andZoneNotLike(String value) {
            addCriterion("zone not like", value, "zone");
            return (Criteria) this;
        }

        public Criteria andZoneIn(List<String> values) {
            addCriterion("zone in", values, "zone");
            return (Criteria) this;
        }

        public Criteria andZoneNotIn(List<String> values) {
            addCriterion("zone not in", values, "zone");
            return (Criteria) this;
        }

        public Criteria andZoneBetween(String value1, String value2) {
            addCriterion("zone between", value1, value2, "zone");
            return (Criteria) this;
        }

        public Criteria andZoneNotBetween(String value1, String value2) {
            addCriterion("zone not between", value1, value2, "zone");
            return (Criteria) this;
        }

        public Criteria andHostCountIsNull() {
            addCriterion("host_count is null");
            return (Criteria) this;
        }

        public Criteria andHostCountIsNotNull() {
            addCriterion("host_count is not null");
            return (Criteria) this;
        }

        public Criteria andHostCountEqualTo(Integer value) {
            addCriterion("host_count =", value, "hostCount");
            return (Criteria) this;
        }

        public Criteria andHostCountNotEqualTo(Integer value) {
            addCriterion("host_count <>", value, "hostCount");
            return (Criteria) this;
        }

        public Criteria andHostCountGreaterThan(Integer value) {
            addCriterion("host_count >", value, "hostCount");
            return (Criteria) this;
        }

        public Criteria andHostCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("host_count >=", value, "hostCount");
            return (Criteria) this;
        }

        public Criteria andHostCountLessThan(Integer value) {
            addCriterion("host_count <", value, "hostCount");
            return (Criteria) this;
        }

        public Criteria andHostCountLessThanOrEqualTo(Integer value) {
            addCriterion("host_count <=", value, "hostCount");
            return (Criteria) this;
        }

        public Criteria andHostCountIn(List<Integer> values) {
            addCriterion("host_count in", values, "hostCount");
            return (Criteria) this;
        }

        public Criteria andHostCountNotIn(List<Integer> values) {
            addCriterion("host_count not in", values, "hostCount");
            return (Criteria) this;
        }

        public Criteria andHostCountBetween(Integer value1, Integer value2) {
            addCriterion("host_count between", value1, value2, "hostCount");
            return (Criteria) this;
        }

        public Criteria andHostCountNotBetween(Integer value1, Integer value2) {
            addCriterion("host_count not between", value1, value2, "hostCount");
            return (Criteria) this;
        }

        public Criteria andVmRunningCountIsNull() {
            addCriterion("vm_running_count is null");
            return (Criteria) this;
        }

        public Criteria andVmRunningCountIsNotNull() {
            addCriterion("vm_running_count is not null");
            return (Criteria) this;
        }

        public Criteria andVmRunningCountEqualTo(Integer value) {
            addCriterion("vm_running_count =", value, "vmRunningCount");
            return (Criteria) this;
        }

        public Criteria andVmRunningCountNotEqualTo(Integer value) {
            addCriterion("vm_running_count <>", value, "vmRunningCount");
            return (Criteria) this;
        }

        public Criteria andVmRunningCountGreaterThan(Integer value) {
            addCriterion("vm_running_count >", value, "vmRunningCount");
            return (Criteria) this;
        }

        public Criteria andVmRunningCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("vm_running_count >=", value, "vmRunningCount");
            return (Criteria) this;
        }

        public Criteria andVmRunningCountLessThan(Integer value) {
            addCriterion("vm_running_count <", value, "vmRunningCount");
            return (Criteria) this;
        }

        public Criteria andVmRunningCountLessThanOrEqualTo(Integer value) {
            addCriterion("vm_running_count <=", value, "vmRunningCount");
            return (Criteria) this;
        }

        public Criteria andVmRunningCountIn(List<Integer> values) {
            addCriterion("vm_running_count in", values, "vmRunningCount");
            return (Criteria) this;
        }

        public Criteria andVmRunningCountNotIn(List<Integer> values) {
            addCriterion("vm_running_count not in", values, "vmRunningCount");
            return (Criteria) this;
        }

        public Criteria andVmRunningCountBetween(Integer value1, Integer value2) {
            addCriterion("vm_running_count between", value1, value2, "vmRunningCount");
            return (Criteria) this;
        }

        public Criteria andVmRunningCountNotBetween(Integer value1, Integer value2) {
            addCriterion("vm_running_count not between", value1, value2, "vmRunningCount");
            return (Criteria) this;
        }

        public Criteria andVmStoppedCountIsNull() {
            addCriterion("vm_stopped_count is null");
            return (Criteria) this;
        }

        public Criteria andVmStoppedCountIsNotNull() {
            addCriterion("vm_stopped_count is not null");
            return (Criteria) this;
        }

        public Criteria andVmStoppedCountEqualTo(Integer value) {
            addCriterion("vm_stopped_count =", value, "vmStoppedCount");
            return (Criteria) this;
        }

        public Criteria andVmStoppedCountNotEqualTo(Integer value) {
            addCriterion("vm_stopped_count <>", value, "vmStoppedCount");
            return (Criteria) this;
        }

        public Criteria andVmStoppedCountGreaterThan(Integer value) {
            addCriterion("vm_stopped_count >", value, "vmStoppedCount");
            return (Criteria) this;
        }

        public Criteria andVmStoppedCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("vm_stopped_count >=", value, "vmStoppedCount");
            return (Criteria) this;
        }

        public Criteria andVmStoppedCountLessThan(Integer value) {
            addCriterion("vm_stopped_count <", value, "vmStoppedCount");
            return (Criteria) this;
        }

        public Criteria andVmStoppedCountLessThanOrEqualTo(Integer value) {
            addCriterion("vm_stopped_count <=", value, "vmStoppedCount");
            return (Criteria) this;
        }

        public Criteria andVmStoppedCountIn(List<Integer> values) {
            addCriterion("vm_stopped_count in", values, "vmStoppedCount");
            return (Criteria) this;
        }

        public Criteria andVmStoppedCountNotIn(List<Integer> values) {
            addCriterion("vm_stopped_count not in", values, "vmStoppedCount");
            return (Criteria) this;
        }

        public Criteria andVmStoppedCountBetween(Integer value1, Integer value2) {
            addCriterion("vm_stopped_count between", value1, value2, "vmStoppedCount");
            return (Criteria) this;
        }

        public Criteria andVmStoppedCountNotBetween(Integer value1, Integer value2) {
            addCriterion("vm_stopped_count not between", value1, value2, "vmStoppedCount");
            return (Criteria) this;
        }

        public Criteria andCpuTotalIsNull() {
            addCriterion("cpu_total is null");
            return (Criteria) this;
        }

        public Criteria andCpuTotalIsNotNull() {
            addCriterion("cpu_total is not null");
            return (Criteria) this;
        }

        public Criteria andCpuTotalEqualTo(Long value) {
            addCriterion("cpu_total =", value, "cpuTotal");
            return (Criteria) this;
        }

        public Criteria andCpuTotalNotEqualTo(Long value) {
            addCriterion("cpu_total <>", value, "cpuTotal");
            return (Criteria) this;
        }

        public Criteria andCpuTotalGreaterThan(Long value) {
            addCriterion("cpu_total >", value, "cpuTotal");
            return (Criteria) this;
        }

        public Criteria andCpuTotalGreaterThanOrEqualTo(Long value) {
            addCriterion("cpu_total >=", value, "cpuTotal");
            return (Criteria) this;
        }

        public Criteria andCpuTotalLessThan(Long value) {
            addCriterion("cpu_total <", value, "cpuTotal");
            return (Criteria) this;
        }

        public Criteria andCpuTotalLessThanOrEqualTo(Long value) {
            addCriterion("cpu_total <=", value, "cpuTotal");
            return (Criteria) this;
        }

        public Criteria andCpuTotalIn(List<Long> values) {
            addCriterion("cpu_total in", values, "cpuTotal");
            return (Criteria) this;
        }

        public Criteria andCpuTotalNotIn(List<Long> values) {
            addCriterion("cpu_total not in", values, "cpuTotal");
            return (Criteria) this;
        }

        public Criteria andCpuTotalBetween(Long value1, Long value2) {
            addCriterion("cpu_total between", value1, value2, "cpuTotal");
            return (Criteria) this;
        }

        public Criteria andCpuTotalNotBetween(Long value1, Long value2) {
            addCriterion("cpu_total not between", value1, value2, "cpuTotal");
            return (Criteria) this;
        }

        public Criteria andCpuAllocatedIsNull() {
            addCriterion("cpu_allocated is null");
            return (Criteria) this;
        }

        public Criteria andCpuAllocatedIsNotNull() {
            addCriterion("cpu_allocated is not null");
            return (Criteria) this;
        }

        public Criteria andCpuAllocatedEqualTo(Long value) {
            addCriterion("cpu_allocated =", value, "cpuAllocated");
            return (Criteria) this;
        }

        public Criteria andCpuAllocatedNotEqualTo(Long value) {
            addCriterion("cpu_allocated <>", value, "cpuAllocated");
            return (Criteria) this;
        }

        public Criteria andCpuAllocatedGreaterThan(Long value) {
            addCriterion("cpu_allocated >", value, "cpuAllocated");
            return (Criteria) this;
        }

        public Criteria andCpuAllocatedGreaterThanOrEqualTo(Long value) {
            addCriterion("cpu_allocated >=", value, "cpuAllocated");
            return (Criteria) this;
        }

        public Criteria andCpuAllocatedLessThan(Long value) {
            addCriterion("cpu_allocated <", value, "cpuAllocated");
            return (Criteria) this;
        }

        public Criteria andCpuAllocatedLessThanOrEqualTo(Long value) {
            addCriterion("cpu_allocated <=", value, "cpuAllocated");
            return (Criteria) this;
        }

        public Criteria andCpuAllocatedIn(List<Long> values) {
            addCriterion("cpu_allocated in", values, "cpuAllocated");
            return (Criteria) this;
        }

        public Criteria andCpuAllocatedNotIn(List<Long> values) {
            addCriterion("cpu_allocated not in", values, "cpuAllocated");
            return (Criteria) this;
        }

        public Criteria andCpuAllocatedBetween(Long value1, Long value2) {
            addCriterion("cpu_allocated between", value1, value2, "cpuAllocated");
            return (Criteria) this;
        }

        public Criteria andCpuAllocatedNotBetween(Long value1, Long value2) {
            addCriterion("cpu_allocated not between", value1, value2, "cpuAllocated");
            return (Criteria) this;
        }

        public Criteria andMemoryTotalIsNull() {
            addCriterion("memory_total is null");
            return (Criteria) this;
        }

        public Criteria andMemoryTotalIsNotNull() {
            addCriterion("memory_total is not null");
            return (Criteria) this;
        }

        public Criteria andMemoryTotalEqualTo(Long value) {
            addCriterion("memory_total =", value, "memoryTotal");
            return (Criteria) this;
        }

        public Criteria andMemoryTotalNotEqualTo(Long value) {
            addCriterion("memory_total <>", value, "memoryTotal");
            return (Criteria) this;
        }

        public Criteria andMemoryTotalGreaterThan(Long value) {
            addCriterion("memory_total >", value, "memoryTotal");
            return (Criteria) this;
        }

        public Criteria andMemoryTotalGreaterThanOrEqualTo(Long value) {
            addCriterion("memory_total >=", value, "memoryTotal");
            return (Criteria) this;
        }

        public Criteria andMemoryTotalLessThan(Long value) {
            addCriterion("memory_total <", value, "memoryTotal");
            return (Criteria) this;
        }

        public Criteria andMemoryTotalLessThanOrEqualTo(Long value) {
            addCriterion("memory_total <=", value, "memoryTotal");
            return (Criteria) this;
        }

        public Criteria andMemoryTotalIn(List<Long> values) {
            addCriterion("memory_total in", values, "memoryTotal");
            return (Criteria) this;
        }

        public Criteria andMemoryTotalNotIn(List<Long> values) {
            addCriterion("memory_total not in", values, "memoryTotal");
            return (Criteria) this;
        }

        public Criteria andMemoryTotalBetween(Long value1, Long value2) {
            addCriterion("memory_total between", value1, value2, "memoryTotal");
            return (Criteria) this;
        }

        public Criteria andMemoryTotalNotBetween(Long value1, Long value2) {
            addCriterion("memory_total not between", value1, value2, "memoryTotal");
            return (Criteria) this;
        }

        public Criteria andMemoryAllocatedIsNull() {
            addCriterion("memory_allocated is null");
            return (Criteria) this;
        }

        public Criteria andMemoryAllocatedIsNotNull() {
            addCriterion("memory_allocated is not null");
            return (Criteria) this;
        }

        public Criteria andMemoryAllocatedEqualTo(Long value) {
            addCriterion("memory_allocated =", value, "memoryAllocated");
            return (Criteria) this;
        }

        public Criteria andMemoryAllocatedNotEqualTo(Long value) {
            addCriterion("memory_allocated <>", value, "memoryAllocated");
            return (Criteria) this;
        }

        public Criteria andMemoryAllocatedGreaterThan(Long value) {
            addCriterion("memory_allocated >", value, "memoryAllocated");
            return (Criteria) this;
        }

        public Criteria andMemoryAllocatedGreaterThanOrEqualTo(Long value) {
            addCriterion("memory_allocated >=", value, "memoryAllocated");
            return (Criteria) this;
        }

        public Criteria andMemoryAllocatedLessThan(Long value) {
            addCriterion("memory_allocated <", value, "memoryAllocated");
            return (Criteria) this;
        }

        public Criteria andMemoryAllocatedLessThanOrEqualTo(Long value) {
            addCriterion("memory_allocated <=", value, "memoryAllocated");
            return (Criteria) this;
        }

        public Criteria andMemoryAllocatedIn(List<Long> values) {
            addCriterion("memory_allocated in", values, "memoryAllocated");
            return (Criteria) this;
        }

        public Criteria andMemoryAllocatedNotIn(List<Long> values) {
            addCriterion("memory_allocated not in", values, "memoryAllocated");
            return (Criteria) this;
        }

        public Criteria andMemoryAllocatedBetween(Long value1, Long value2) {
            addCriterion("memory_allocated between", value1, value2, "memoryAllocated");
            return (Criteria) this;
        }

        public Criteria andMemoryAllocatedNotBetween(Long value1, Long value2) {
            addCriterion("memory_allocated not between", value1, value2, "memoryAllocated");
            return (Criteria) this;
        }

        public Criteria andLastSyncTimestampIsNull() {
            addCriterion("last_sync_timestamp is null");
            return (Criteria) this;
        }

        public Criteria andLastSyncTimestampIsNotNull() {
            addCriterion("last_sync_timestamp is not null");
            return (Criteria) this;
        }

        public Criteria andLastSyncTimestampEqualTo(Long value) {
            addCriterion("last_sync_timestamp =", value, "lastSyncTimestamp");
            return (Criteria) this;
        }

        public Criteria andLastSyncTimestampNotEqualTo(Long value) {
            addCriterion("last_sync_timestamp <>", value, "lastSyncTimestamp");
            return (Criteria) this;
        }

        public Criteria andLastSyncTimestampGreaterThan(Long value) {
            addCriterion("last_sync_timestamp >", value, "lastSyncTimestamp");
            return (Criteria) this;
        }

        public Criteria andLastSyncTimestampGreaterThanOrEqualTo(Long value) {
            addCriterion("last_sync_timestamp >=", value, "lastSyncTimestamp");
            return (Criteria) this;
        }

        public Criteria andLastSyncTimestampLessThan(Long value) {
            addCriterion("last_sync_timestamp <", value, "lastSyncTimestamp");
            return (Criteria) this;
        }

        public Criteria andLastSyncTimestampLessThanOrEqualTo(Long value) {
            addCriterion("last_sync_timestamp <=", value, "lastSyncTimestamp");
            return (Criteria) this;
        }

        public Criteria andLastSyncTimestampIn(List<Long> values) {
            addCriterion("last_sync_timestamp in", values, "lastSyncTimestamp");
            return (Criteria) this;
        }

        public Criteria andLastSyncTimestampNotIn(List<Long> values) {
            addCriterion("last_sync_timestamp not in", values, "lastSyncTimestamp");
            return (Criteria) this;
        }

        public Criteria andLastSyncTimestampBetween(Long value1, Long value2) {
            addCriterion("last_sync_timestamp between", value1, value2, "lastSyncTimestamp");
            return (Criteria) this;
        }

        public Criteria andLastSyncTimestampNotBetween(Long value1, Long value2) {
            addCriterion("last_sync_timestamp not between", value1, value2, "lastSyncTimestamp");
            return (Criteria) this;
        }

        public Criteria andSqlCriterion(String value) {
            addCriterion("(" + value + ")");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cloud_cluster
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cloud_cluster
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}