package com.fit2cloud.commons.server.base.domain;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

public class FileStore implements Serializable {
    @ApiModelProperty("")
    private String id;

    @ApiModelProperty("文件分类")
    private String businessKey;

    @ApiModelProperty(value = "名称", required = true)
    private String name;

    @ApiModelProperty(value = "文件大小", required = true)
    private Long size;

    @ApiModelProperty("创建时间")
    private Long createTime;

    @ApiModelProperty("文件")
    private byte[] file;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table file_store
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_store.id
     *
     * @return the value of file_store.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_store.id
     *
     * @param id the value for file_store.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_store.business_key
     *
     * @return the value of file_store.business_key
     *
     * @mbg.generated
     */
    public String getBusinessKey() {
        return businessKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_store.business_key
     *
     * @param businessKey the value for file_store.business_key
     *
     * @mbg.generated
     */
    public void setBusinessKey(String businessKey) {
        this.businessKey = businessKey == null ? null : businessKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_store.name
     *
     * @return the value of file_store.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_store.name
     *
     * @param name the value for file_store.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_store.size
     *
     * @return the value of file_store.size
     *
     * @mbg.generated
     */
    public Long getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_store.size
     *
     * @param size the value for file_store.size
     *
     * @mbg.generated
     */
    public void setSize(Long size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_store.create_time
     *
     * @return the value of file_store.create_time
     *
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_store.create_time
     *
     * @param createTime the value for file_store.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_store.file
     *
     * @return the value of file_store.file
     *
     * @mbg.generated
     */
    public byte[] getFile() {
        return file;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_store.file
     *
     * @param file the value for file_store.file
     *
     * @mbg.generated
     */
    public void setFile(byte[] file) {
        this.file = file;
    }
}