package com.fit2cloud.commons.server.base.domain;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.Date;

public class FlowModel implements Serializable {
    @ApiModelProperty(value = "流程模型ID", required = true)
    private String modelId;

    @ApiModelProperty(value = "模型名称", required = true)
    private String modelName;

    @ApiModelProperty(value = "版本", required = true)
    private Long modelVersion;

    @ApiModelProperty("创建者")
    private String modelCreator;

    @ApiModelProperty("创建时间")
    private Date modelTime;

    @ApiModelProperty("部署ID")
    private String deployId;

    @ApiModelProperty("模块ID")
    private String module;

    @ApiModelProperty(value = "模型内容", required = true)
    private String modelContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table flow_model
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_model.model_id
     *
     * @return the value of flow_model.model_id
     *
     * @mbg.generated
     */
    public String getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_model.model_id
     *
     * @param modelId the value for flow_model.model_id
     *
     * @mbg.generated
     */
    public void setModelId(String modelId) {
        this.modelId = modelId == null ? null : modelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_model.model_name
     *
     * @return the value of flow_model.model_name
     *
     * @mbg.generated
     */
    public String getModelName() {
        return modelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_model.model_name
     *
     * @param modelName the value for flow_model.model_name
     *
     * @mbg.generated
     */
    public void setModelName(String modelName) {
        this.modelName = modelName == null ? null : modelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_model.model_version
     *
     * @return the value of flow_model.model_version
     *
     * @mbg.generated
     */
    public Long getModelVersion() {
        return modelVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_model.model_version
     *
     * @param modelVersion the value for flow_model.model_version
     *
     * @mbg.generated
     */
    public void setModelVersion(Long modelVersion) {
        this.modelVersion = modelVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_model.model_creator
     *
     * @return the value of flow_model.model_creator
     *
     * @mbg.generated
     */
    public String getModelCreator() {
        return modelCreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_model.model_creator
     *
     * @param modelCreator the value for flow_model.model_creator
     *
     * @mbg.generated
     */
    public void setModelCreator(String modelCreator) {
        this.modelCreator = modelCreator == null ? null : modelCreator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_model.model_time
     *
     * @return the value of flow_model.model_time
     *
     * @mbg.generated
     */
    public Date getModelTime() {
        return modelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_model.model_time
     *
     * @param modelTime the value for flow_model.model_time
     *
     * @mbg.generated
     */
    public void setModelTime(Date modelTime) {
        this.modelTime = modelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_model.deploy_id
     *
     * @return the value of flow_model.deploy_id
     *
     * @mbg.generated
     */
    public String getDeployId() {
        return deployId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_model.deploy_id
     *
     * @param deployId the value for flow_model.deploy_id
     *
     * @mbg.generated
     */
    public void setDeployId(String deployId) {
        this.deployId = deployId == null ? null : deployId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_model.module
     *
     * @return the value of flow_model.module
     *
     * @mbg.generated
     */
    public String getModule() {
        return module;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_model.module
     *
     * @param module the value for flow_model.module
     *
     * @mbg.generated
     */
    public void setModule(String module) {
        this.module = module == null ? null : module.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_model.model_content
     *
     * @return the value of flow_model.model_content
     *
     * @mbg.generated
     */
    public String getModelContent() {
        return modelContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_model.model_content
     *
     * @param modelContent the value for flow_model.model_content
     *
     * @mbg.generated
     */
    public void setModelContent(String modelContent) {
        this.modelContent = modelContent == null ? null : modelContent.trim();
    }
}