package com.fit2cloud.commons.server.base.domain;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

public class FlowEvent implements Serializable {
    @ApiModelProperty("事件ID")
    private Integer id;

    @ApiModelProperty("事件名称")
    private String name;

    @ApiModelProperty("执行器")
    private String executor;

    @ApiModelProperty("模型ID")
    private String modelId;

    @ApiModelProperty("环节ID")
    private String activityId;

    @ApiModelProperty("环节ID")
    private Integer step;

    @ApiModelProperty("事件类型")
    private String type;

    @ApiModelProperty("触发时机")
    private String position;

    @ApiModelProperty("触发操作")
    private String operation;

    @ApiModelProperty("模块ID")
    private String module;

    @ApiModelProperty("参数")
    private String arguments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table flow_event
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_event.id
     *
     * @return the value of flow_event.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_event.id
     *
     * @param id the value for flow_event.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_event.name
     *
     * @return the value of flow_event.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_event.name
     *
     * @param name the value for flow_event.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_event.executor
     *
     * @return the value of flow_event.executor
     *
     * @mbg.generated
     */
    public String getExecutor() {
        return executor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_event.executor
     *
     * @param executor the value for flow_event.executor
     *
     * @mbg.generated
     */
    public void setExecutor(String executor) {
        this.executor = executor == null ? null : executor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_event.model_id
     *
     * @return the value of flow_event.model_id
     *
     * @mbg.generated
     */
    public String getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_event.model_id
     *
     * @param modelId the value for flow_event.model_id
     *
     * @mbg.generated
     */
    public void setModelId(String modelId) {
        this.modelId = modelId == null ? null : modelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_event.activity_id
     *
     * @return the value of flow_event.activity_id
     *
     * @mbg.generated
     */
    public String getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_event.activity_id
     *
     * @param activityId the value for flow_event.activity_id
     *
     * @mbg.generated
     */
    public void setActivityId(String activityId) {
        this.activityId = activityId == null ? null : activityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_event.step
     *
     * @return the value of flow_event.step
     *
     * @mbg.generated
     */
    public Integer getStep() {
        return step;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_event.step
     *
     * @param step the value for flow_event.step
     *
     * @mbg.generated
     */
    public void setStep(Integer step) {
        this.step = step;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_event.type
     *
     * @return the value of flow_event.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_event.type
     *
     * @param type the value for flow_event.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_event.position
     *
     * @return the value of flow_event.position
     *
     * @mbg.generated
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_event.position
     *
     * @param position the value for flow_event.position
     *
     * @mbg.generated
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_event.operation
     *
     * @return the value of flow_event.operation
     *
     * @mbg.generated
     */
    public String getOperation() {
        return operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_event.operation
     *
     * @param operation the value for flow_event.operation
     *
     * @mbg.generated
     */
    public void setOperation(String operation) {
        this.operation = operation == null ? null : operation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_event.module
     *
     * @return the value of flow_event.module
     *
     * @mbg.generated
     */
    public String getModule() {
        return module;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_event.module
     *
     * @param module the value for flow_event.module
     *
     * @mbg.generated
     */
    public void setModule(String module) {
        this.module = module == null ? null : module.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_event.arguments
     *
     * @return the value of flow_event.arguments
     *
     * @mbg.generated
     */
    public String getArguments() {
        return arguments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_event.arguments
     *
     * @param arguments the value for flow_event.arguments
     *
     * @mbg.generated
     */
    public void setArguments(String arguments) {
        this.arguments = arguments == null ? null : arguments.trim();
    }
}