package com.fit2cloud.commons.server.base.domain;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

public class FlowLink implements Serializable {
    @ApiModelProperty(value = "", required = true)
    private String linkId;

    @ApiModelProperty("环节标识")
    private String linkKey;

    @ApiModelProperty("环节类型")
    private String linkType;

    @ApiModelProperty("环节名称")
    private String linkAlias;

    @ApiModelProperty("是否启用")
    private Boolean enable;

    @ApiModelProperty("创建时间")
    private Long createTime;

    @ApiModelProperty("模块ID")
    private String module;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table flow_link
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_link.link_id
     *
     * @return the value of flow_link.link_id
     *
     * @mbg.generated
     */
    public String getLinkId() {
        return linkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_link.link_id
     *
     * @param linkId the value for flow_link.link_id
     *
     * @mbg.generated
     */
    public void setLinkId(String linkId) {
        this.linkId = linkId == null ? null : linkId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_link.link_key
     *
     * @return the value of flow_link.link_key
     *
     * @mbg.generated
     */
    public String getLinkKey() {
        return linkKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_link.link_key
     *
     * @param linkKey the value for flow_link.link_key
     *
     * @mbg.generated
     */
    public void setLinkKey(String linkKey) {
        this.linkKey = linkKey == null ? null : linkKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_link.link_type
     *
     * @return the value of flow_link.link_type
     *
     * @mbg.generated
     */
    public String getLinkType() {
        return linkType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_link.link_type
     *
     * @param linkType the value for flow_link.link_type
     *
     * @mbg.generated
     */
    public void setLinkType(String linkType) {
        this.linkType = linkType == null ? null : linkType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_link.link_alias
     *
     * @return the value of flow_link.link_alias
     *
     * @mbg.generated
     */
    public String getLinkAlias() {
        return linkAlias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_link.link_alias
     *
     * @param linkAlias the value for flow_link.link_alias
     *
     * @mbg.generated
     */
    public void setLinkAlias(String linkAlias) {
        this.linkAlias = linkAlias == null ? null : linkAlias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_link.enable
     *
     * @return the value of flow_link.enable
     *
     * @mbg.generated
     */
    public Boolean getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_link.enable
     *
     * @param enable the value for flow_link.enable
     *
     * @mbg.generated
     */
    public void setEnable(Boolean enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_link.create_time
     *
     * @return the value of flow_link.create_time
     *
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_link.create_time
     *
     * @param createTime the value for flow_link.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_link.module
     *
     * @return the value of flow_link.module
     *
     * @mbg.generated
     */
    public String getModule() {
        return module;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_link.module
     *
     * @param module the value for flow_link.module
     *
     * @mbg.generated
     */
    public void setModule(String module) {
        this.module = module == null ? null : module.trim();
    }
}