package com.fit2cloud.commons.server.base.domain;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

public class I18nWithBLOBs extends I18n implements Serializable {
    @ApiModelProperty("web 国际化 json")
    private String webBundles;

    @ApiModelProperty("server 国际化 json")
    private String serverBundles;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table i18n
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i18n.web_bundles
     *
     * @return the value of i18n.web_bundles
     *
     * @mbg.generated
     */
    public String getWebBundles() {
        return webBundles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i18n.web_bundles
     *
     * @param webBundles the value for i18n.web_bundles
     *
     * @mbg.generated
     */
    public void setWebBundles(String webBundles) {
        this.webBundles = webBundles == null ? null : webBundles.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i18n.server_bundles
     *
     * @return the value of i18n.server_bundles
     *
     * @mbg.generated
     */
    public String getServerBundles() {
        return serverBundles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i18n.server_bundles
     *
     * @param serverBundles the value for i18n.server_bundles
     *
     * @mbg.generated
     */
    public void setServerBundles(String serverBundles) {
        this.serverBundles = serverBundles == null ? null : serverBundles.trim();
    }
}