package com.fit2cloud.commons.server.base.domain;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

public class MenuPreference implements Serializable {
    @ApiModelProperty("")
    private String id;

    @ApiModelProperty("用户ID")
    private String userId;

    @ApiModelProperty("模块ID")
    private String moduleId;

    @ApiModelProperty("菜单ID")
    private String menuId;

    @ApiModelProperty("排序")
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table menu_preference
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_preference.id
     *
     * @return the value of menu_preference.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_preference.id
     *
     * @param id the value for menu_preference.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_preference.user_id
     *
     * @return the value of menu_preference.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_preference.user_id
     *
     * @param userId the value for menu_preference.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_preference.module_id
     *
     * @return the value of menu_preference.module_id
     *
     * @mbg.generated
     */
    public String getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_preference.module_id
     *
     * @param moduleId the value for menu_preference.module_id
     *
     * @mbg.generated
     */
    public void setModuleId(String moduleId) {
        this.moduleId = moduleId == null ? null : moduleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_preference.menu_id
     *
     * @return the value of menu_preference.menu_id
     *
     * @mbg.generated
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_preference.menu_id
     *
     * @param menuId the value for menu_preference.menu_id
     *
     * @mbg.generated
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId == null ? null : menuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_preference.sort
     *
     * @return the value of menu_preference.sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_preference.sort
     *
     * @param sort the value for menu_preference.sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}