package com.fit2cloud.commons.server.base.domain;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

public class Plugin implements Serializable {
    @ApiModelProperty("插件ID")
    private String id;

    @ApiModelProperty(value = "名称", required = true)
    private String name;

    @ApiModelProperty("描述")
    private String description;

    @ApiModelProperty(value = "插件版本", required = true)
    private String version;

    @ApiModelProperty(value = "作者", required = true)
    private String owner;

    @ApiModelProperty("状态")
    private String status;

    @ApiModelProperty(value = "插件类型", required = true)
    private String pluginType;

    @ApiModelProperty("更新时间")
    private Long updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table plugin
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugin.id
     *
     * @return the value of plugin.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugin.id
     *
     * @param id the value for plugin.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugin.name
     *
     * @return the value of plugin.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugin.name
     *
     * @param name the value for plugin.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugin.description
     *
     * @return the value of plugin.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugin.description
     *
     * @param description the value for plugin.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugin.version
     *
     * @return the value of plugin.version
     *
     * @mbg.generated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugin.version
     *
     * @param version the value for plugin.version
     *
     * @mbg.generated
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugin.owner
     *
     * @return the value of plugin.owner
     *
     * @mbg.generated
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugin.owner
     *
     * @param owner the value for plugin.owner
     *
     * @mbg.generated
     */
    public void setOwner(String owner) {
        this.owner = owner == null ? null : owner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugin.status
     *
     * @return the value of plugin.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugin.status
     *
     * @param status the value for plugin.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugin.plugin_type
     *
     * @return the value of plugin.plugin_type
     *
     * @mbg.generated
     */
    public String getPluginType() {
        return pluginType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugin.plugin_type
     *
     * @param pluginType the value for plugin.plugin_type
     *
     * @mbg.generated
     */
    public void setPluginType(String pluginType) {
        this.pluginType = pluginType == null ? null : pluginType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugin.update_time
     *
     * @return the value of plugin.update_time
     *
     * @mbg.generated
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugin.update_time
     *
     * @param updateTime the value for plugin.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }
}