package com.fit2cloud.commons.server.base.domain;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

public class TagValue implements Serializable {
    @ApiModelProperty("")
    private String id;

    @ApiModelProperty("标签标识")
    private String tagKey;

    @ApiModelProperty("标签值")
    private String tagValue;

    @ApiModelProperty("标签值别名")
    private String tagValueAlias;

    @ApiModelProperty("创建时间")
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tag_value
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_value.id
     *
     * @return the value of tag_value.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_value.id
     *
     * @param id the value for tag_value.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_value.tag_key
     *
     * @return the value of tag_value.tag_key
     *
     * @mbg.generated
     */
    public String getTagKey() {
        return tagKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_value.tag_key
     *
     * @param tagKey the value for tag_value.tag_key
     *
     * @mbg.generated
     */
    public void setTagKey(String tagKey) {
        this.tagKey = tagKey == null ? null : tagKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_value.tag_value
     *
     * @return the value of tag_value.tag_value
     *
     * @mbg.generated
     */
    public String getTagValue() {
        return tagValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_value.tag_value
     *
     * @param tagValue the value for tag_value.tag_value
     *
     * @mbg.generated
     */
    public void setTagValue(String tagValue) {
        this.tagValue = tagValue == null ? null : tagValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_value.tag_value_alias
     *
     * @return the value of tag_value.tag_value_alias
     *
     * @mbg.generated
     */
    public String getTagValueAlias() {
        return tagValueAlias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_value.tag_value_alias
     *
     * @param tagValueAlias the value for tag_value.tag_value_alias
     *
     * @mbg.generated
     */
    public void setTagValueAlias(String tagValueAlias) {
        this.tagValueAlias = tagValueAlias == null ? null : tagValueAlias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_value.create_time
     *
     * @return the value of tag_value.create_time
     *
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_value.create_time
     *
     * @param createTime the value for tag_value.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }
}